// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proto/clarifai/auth/scope/scope.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:clarifai.auth.scope.ScopeList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ScopeList {
    // message fields
    ///  These are the list of low-level scopes to check from the enum below.
    // @@protoc_insertion_point(field:clarifai.auth.scope.ScopeList.scopes)
    pub scopes: ::std::vec::Vec<::protobuf::EnumOrUnknown<S>>,
    ///  This is a list of fully qualified grpc names to check.
    // @@protoc_insertion_point(field:clarifai.auth.scope.ScopeList.endpoints)
    pub endpoints: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:clarifai.auth.scope.ScopeList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ScopeList {
    fn default() -> &'a ScopeList {
        <ScopeList as ::protobuf::Message>::default_instance()
    }
}

impl ScopeList {
    pub fn new() -> ScopeList {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "scopes",
            |m: &ScopeList| { &m.scopes },
            |m: &mut ScopeList| { &mut m.scopes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "endpoints",
            |m: &ScopeList| { &m.endpoints },
            |m: &mut ScopeList| { &mut m.endpoints },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ScopeList>(
            "ScopeList",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ScopeList {
    const NAME: &'static str = "ScopeList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.scopes.push(is.read_enum_or_unknown()?);
                },
                10 => {
                    ::protobuf::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.scopes)?
                },
                18 => {
                    self.endpoints.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.scopes {
            my_size += ::protobuf::rt::int32_size(1, value.value());
        };
        for value in &self.endpoints {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.scopes {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(v))?;
        };
        for v in &self.endpoints {
            os.write_string(2, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ScopeList {
        ScopeList::new()
    }

    fn clear(&mut self) {
        self.scopes.clear();
        self.endpoints.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ScopeList {
        static instance: ScopeList = ScopeList {
            scopes: ::std::vec::Vec::new(),
            endpoints: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ScopeList {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ScopeList").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ScopeList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ScopeList {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Next index: 41
///  NOTE: When updating the list of "clarifai_exposed" scopes, please also
///  update the TestScopes function in main_key_test.go and TestGetExposedScopes function in
///  scope_test.go
///
///  The dependencies listed for each scope are simply recommendations so that a user
///  cannot make a key that would be useless. Beyond the key creation they are not enforced
///  but rather the scopes are enforce when data is accessed.
///
///
///  There is the following conventions in place, make sure you add them to the scopes for all new
///  resource types:
///
///  1. *_Add requires the corresponding _Get.
///  2. *_Delete requires the corresponding _Add and _Get.
///  3. *_Patch is deprecated and not check anywhere.
///
///  Think of the dependencies in this file at the DB level. If you cannot make a DB call to Get, Add
///  or Delete a resource without having access to another resource then you should add it here. That
///  should for the most part be the same resource type. In service.proto for the API level you will
///  also specify cl_depending_scopes for each API endpoint. Those cover cases where an endpoint
///  might need to access more than just that one resource type in order to operate (ie. API handlers
///  that make multiple DB calls of various resource types likely have more cl_depending_scopes than
///  the ones listed below). For example: PostCollectors to create a collector we make sure that you
///  can do model predictions, get concepts, etc. so that you don't have a collector that would be
///  useless at the end of that API handler but below you can see that the dependencies of Collector
///  scopes are only on other Collector scopes.
///
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:clarifai.auth.scope.S)
pub enum S {
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.undef)
    undef = 0,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.All)
    All = 1,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Predict)
    Predict = 2,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Inputs_Add)
    Inputs_Add = 4,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Inputs_Get)
    Inputs_Get = 5,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Inputs_Patch)
    Inputs_Patch = 7,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Inputs_Delete)
    Inputs_Delete = 8,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Outputs_Patch)
    Outputs_Patch = 9,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Concepts_Add)
    Concepts_Add = 10,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Concepts_Get)
    Concepts_Get = 11,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Concepts_Patch)
    Concepts_Patch = 12,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Concepts_Delete)
    Concepts_Delete = 13,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Models_Add)
    Models_Add = 14,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Models_Get)
    Models_Get = 15,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Models_Patch)
    Models_Patch = 16,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Models_Delete)
    Models_Delete = 17,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Models_Train)
    Models_Train = 26,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Models_Sync)
    Models_Sync = 27,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.ModelExports_Get)
    ModelExports_Get = 142,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.ModelExports_Add)
    ModelExports_Add = 143,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Workflows_Add)
    Workflows_Add = 18,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Workflows_Get)
    Workflows_Get = 19,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Workflows_Patch)
    Workflows_Patch = 20,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Workflows_Delete)
    Workflows_Delete = 21,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.WorkflowMetrics_Get)
    WorkflowMetrics_Get = 96,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.WorkflowMetrics_Add)
    WorkflowMetrics_Add = 97,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.WorkflowMetrics_Delete)
    WorkflowMetrics_Delete = 98,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.TSNEVisualizations_Add)
    TSNEVisualizations_Add = 24,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.TSNEVisualizations_Get)
    TSNEVisualizations_Get = 25,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Annotations_Add)
    Annotations_Add = 37,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Annotations_Get)
    Annotations_Get = 38,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Annotations_Patch)
    Annotations_Patch = 39,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Annotations_Delete)
    Annotations_Delete = 40,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Collectors_Add)
    Collectors_Add = 41,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Collectors_Get)
    Collectors_Get = 42,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Collectors_Delete)
    Collectors_Delete = 43,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Apps_Add)
    Apps_Add = 44,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Apps_Get)
    Apps_Get = 45,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Apps_Delete)
    Apps_Delete = 46,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Keys_Add)
    Keys_Add = 47,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Keys_Get)
    Keys_Get = 48,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Keys_Delete)
    Keys_Delete = 49,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Collaborators_Add)
    Collaborators_Add = 51,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Collaborators_Get)
    Collaborators_Get = 50,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Collaborators_Delete)
    Collaborators_Delete = 52,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Metrics_Add)
    Metrics_Add = 54,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Metrics_Get)
    Metrics_Get = 53,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Metrics_Delete)
    Metrics_Delete = 63,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Tasks_Add)
    Tasks_Add = 55,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Tasks_Get)
    Tasks_Get = 56,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Tasks_Delete)
    Tasks_Delete = 70,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.PasswordPolicies_Add)
    PasswordPolicies_Add = 57,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.PasswordPolicies_Get)
    PasswordPolicies_Get = 58,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.PasswordPolicies_Delete)
    PasswordPolicies_Delete = 59,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.LabelOrders_Get)
    LabelOrders_Get = 67,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.LabelOrders_Add)
    LabelOrders_Add = 68,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.LabelOrders_Delete)
    LabelOrders_Delete = 69,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.UserFeatureConfigs_Get)
    UserFeatureConfigs_Get = 71,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.FindDuplicateAnnotationsJobs_Add)
    FindDuplicateAnnotationsJobs_Add = 102,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.FindDuplicateAnnotationsJobs_Get)
    FindDuplicateAnnotationsJobs_Get = 103,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.FindDuplicateAnnotationsJobs_Delete)
    FindDuplicateAnnotationsJobs_Delete = 104,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Datasets_Get)
    Datasets_Get = 105,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Datasets_Add)
    Datasets_Add = 106,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Datasets_Delete)
    Datasets_Delete = 107,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Modules_Add)
    Modules_Add = 108,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Modules_Get)
    Modules_Get = 109,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Modules_Delete)
    Modules_Delete = 110,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.InstalledModuleVersions_Add)
    InstalledModuleVersions_Add = 111,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.InstalledModuleVersions_Get)
    InstalledModuleVersions_Get = 112,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.InstalledModuleVersions_Delete)
    InstalledModuleVersions_Delete = 113,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Search)
    Search = 3,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.SavedSearch_Get)
    SavedSearch_Get = 114,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.SavedSearch_Add)
    SavedSearch_Add = 115,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.SavedSearch_Delete)
    SavedSearch_Delete = 116,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.ModelVersionPublications_Add)
    ModelVersionPublications_Add = 117,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.ModelVersionPublications_Delete)
    ModelVersionPublications_Delete = 118,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.WorkflowPublications_Add)
    WorkflowPublications_Add = 119,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.WorkflowPublications_Delete)
    WorkflowPublications_Delete = 120,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.BulkOperation_Add)
    BulkOperation_Add = 121,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.BulkOperation_Get)
    BulkOperation_Get = 122,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.BulkOperation_Delete)
    BulkOperation_Delete = 123,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.HistoricalUsage_Get)
    HistoricalUsage_Get = 124,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Uploads_Get)
    Uploads_Get = 128,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Uploads_Add)
    Uploads_Add = 129,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Uploads_Delete)
    Uploads_Delete = 130,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Runners_Get)
    Runners_Get = 131,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Runners_Add)
    Runners_Add = 132,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.Runners_Delete)
    Runners_Delete = 133,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.RunnerItems_Get)
    RunnerItems_Get = 134,
    // @@protoc_insertion_point(enum_value:clarifai.auth.scope.S.RunnerItems_Add)
    RunnerItems_Add = 135,
}

impl ::protobuf::Enum for S {
    const NAME: &'static str = "S";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<S> {
        match value {
            0 => ::std::option::Option::Some(S::undef),
            1 => ::std::option::Option::Some(S::All),
            2 => ::std::option::Option::Some(S::Predict),
            4 => ::std::option::Option::Some(S::Inputs_Add),
            5 => ::std::option::Option::Some(S::Inputs_Get),
            7 => ::std::option::Option::Some(S::Inputs_Patch),
            8 => ::std::option::Option::Some(S::Inputs_Delete),
            9 => ::std::option::Option::Some(S::Outputs_Patch),
            10 => ::std::option::Option::Some(S::Concepts_Add),
            11 => ::std::option::Option::Some(S::Concepts_Get),
            12 => ::std::option::Option::Some(S::Concepts_Patch),
            13 => ::std::option::Option::Some(S::Concepts_Delete),
            14 => ::std::option::Option::Some(S::Models_Add),
            15 => ::std::option::Option::Some(S::Models_Get),
            16 => ::std::option::Option::Some(S::Models_Patch),
            17 => ::std::option::Option::Some(S::Models_Delete),
            26 => ::std::option::Option::Some(S::Models_Train),
            27 => ::std::option::Option::Some(S::Models_Sync),
            142 => ::std::option::Option::Some(S::ModelExports_Get),
            143 => ::std::option::Option::Some(S::ModelExports_Add),
            18 => ::std::option::Option::Some(S::Workflows_Add),
            19 => ::std::option::Option::Some(S::Workflows_Get),
            20 => ::std::option::Option::Some(S::Workflows_Patch),
            21 => ::std::option::Option::Some(S::Workflows_Delete),
            96 => ::std::option::Option::Some(S::WorkflowMetrics_Get),
            97 => ::std::option::Option::Some(S::WorkflowMetrics_Add),
            98 => ::std::option::Option::Some(S::WorkflowMetrics_Delete),
            24 => ::std::option::Option::Some(S::TSNEVisualizations_Add),
            25 => ::std::option::Option::Some(S::TSNEVisualizations_Get),
            37 => ::std::option::Option::Some(S::Annotations_Add),
            38 => ::std::option::Option::Some(S::Annotations_Get),
            39 => ::std::option::Option::Some(S::Annotations_Patch),
            40 => ::std::option::Option::Some(S::Annotations_Delete),
            41 => ::std::option::Option::Some(S::Collectors_Add),
            42 => ::std::option::Option::Some(S::Collectors_Get),
            43 => ::std::option::Option::Some(S::Collectors_Delete),
            44 => ::std::option::Option::Some(S::Apps_Add),
            45 => ::std::option::Option::Some(S::Apps_Get),
            46 => ::std::option::Option::Some(S::Apps_Delete),
            47 => ::std::option::Option::Some(S::Keys_Add),
            48 => ::std::option::Option::Some(S::Keys_Get),
            49 => ::std::option::Option::Some(S::Keys_Delete),
            51 => ::std::option::Option::Some(S::Collaborators_Add),
            50 => ::std::option::Option::Some(S::Collaborators_Get),
            52 => ::std::option::Option::Some(S::Collaborators_Delete),
            54 => ::std::option::Option::Some(S::Metrics_Add),
            53 => ::std::option::Option::Some(S::Metrics_Get),
            63 => ::std::option::Option::Some(S::Metrics_Delete),
            55 => ::std::option::Option::Some(S::Tasks_Add),
            56 => ::std::option::Option::Some(S::Tasks_Get),
            70 => ::std::option::Option::Some(S::Tasks_Delete),
            57 => ::std::option::Option::Some(S::PasswordPolicies_Add),
            58 => ::std::option::Option::Some(S::PasswordPolicies_Get),
            59 => ::std::option::Option::Some(S::PasswordPolicies_Delete),
            67 => ::std::option::Option::Some(S::LabelOrders_Get),
            68 => ::std::option::Option::Some(S::LabelOrders_Add),
            69 => ::std::option::Option::Some(S::LabelOrders_Delete),
            71 => ::std::option::Option::Some(S::UserFeatureConfigs_Get),
            102 => ::std::option::Option::Some(S::FindDuplicateAnnotationsJobs_Add),
            103 => ::std::option::Option::Some(S::FindDuplicateAnnotationsJobs_Get),
            104 => ::std::option::Option::Some(S::FindDuplicateAnnotationsJobs_Delete),
            105 => ::std::option::Option::Some(S::Datasets_Get),
            106 => ::std::option::Option::Some(S::Datasets_Add),
            107 => ::std::option::Option::Some(S::Datasets_Delete),
            108 => ::std::option::Option::Some(S::Modules_Add),
            109 => ::std::option::Option::Some(S::Modules_Get),
            110 => ::std::option::Option::Some(S::Modules_Delete),
            111 => ::std::option::Option::Some(S::InstalledModuleVersions_Add),
            112 => ::std::option::Option::Some(S::InstalledModuleVersions_Get),
            113 => ::std::option::Option::Some(S::InstalledModuleVersions_Delete),
            3 => ::std::option::Option::Some(S::Search),
            114 => ::std::option::Option::Some(S::SavedSearch_Get),
            115 => ::std::option::Option::Some(S::SavedSearch_Add),
            116 => ::std::option::Option::Some(S::SavedSearch_Delete),
            117 => ::std::option::Option::Some(S::ModelVersionPublications_Add),
            118 => ::std::option::Option::Some(S::ModelVersionPublications_Delete),
            119 => ::std::option::Option::Some(S::WorkflowPublications_Add),
            120 => ::std::option::Option::Some(S::WorkflowPublications_Delete),
            121 => ::std::option::Option::Some(S::BulkOperation_Add),
            122 => ::std::option::Option::Some(S::BulkOperation_Get),
            123 => ::std::option::Option::Some(S::BulkOperation_Delete),
            124 => ::std::option::Option::Some(S::HistoricalUsage_Get),
            128 => ::std::option::Option::Some(S::Uploads_Get),
            129 => ::std::option::Option::Some(S::Uploads_Add),
            130 => ::std::option::Option::Some(S::Uploads_Delete),
            131 => ::std::option::Option::Some(S::Runners_Get),
            132 => ::std::option::Option::Some(S::Runners_Add),
            133 => ::std::option::Option::Some(S::Runners_Delete),
            134 => ::std::option::Option::Some(S::RunnerItems_Get),
            135 => ::std::option::Option::Some(S::RunnerItems_Add),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<S> {
        match str {
            "undef" => ::std::option::Option::Some(S::undef),
            "All" => ::std::option::Option::Some(S::All),
            "Predict" => ::std::option::Option::Some(S::Predict),
            "Inputs_Add" => ::std::option::Option::Some(S::Inputs_Add),
            "Inputs_Get" => ::std::option::Option::Some(S::Inputs_Get),
            "Inputs_Patch" => ::std::option::Option::Some(S::Inputs_Patch),
            "Inputs_Delete" => ::std::option::Option::Some(S::Inputs_Delete),
            "Outputs_Patch" => ::std::option::Option::Some(S::Outputs_Patch),
            "Concepts_Add" => ::std::option::Option::Some(S::Concepts_Add),
            "Concepts_Get" => ::std::option::Option::Some(S::Concepts_Get),
            "Concepts_Patch" => ::std::option::Option::Some(S::Concepts_Patch),
            "Concepts_Delete" => ::std::option::Option::Some(S::Concepts_Delete),
            "Models_Add" => ::std::option::Option::Some(S::Models_Add),
            "Models_Get" => ::std::option::Option::Some(S::Models_Get),
            "Models_Patch" => ::std::option::Option::Some(S::Models_Patch),
            "Models_Delete" => ::std::option::Option::Some(S::Models_Delete),
            "Models_Train" => ::std::option::Option::Some(S::Models_Train),
            "Models_Sync" => ::std::option::Option::Some(S::Models_Sync),
            "ModelExports_Get" => ::std::option::Option::Some(S::ModelExports_Get),
            "ModelExports_Add" => ::std::option::Option::Some(S::ModelExports_Add),
            "Workflows_Add" => ::std::option::Option::Some(S::Workflows_Add),
            "Workflows_Get" => ::std::option::Option::Some(S::Workflows_Get),
            "Workflows_Patch" => ::std::option::Option::Some(S::Workflows_Patch),
            "Workflows_Delete" => ::std::option::Option::Some(S::Workflows_Delete),
            "WorkflowMetrics_Get" => ::std::option::Option::Some(S::WorkflowMetrics_Get),
            "WorkflowMetrics_Add" => ::std::option::Option::Some(S::WorkflowMetrics_Add),
            "WorkflowMetrics_Delete" => ::std::option::Option::Some(S::WorkflowMetrics_Delete),
            "TSNEVisualizations_Add" => ::std::option::Option::Some(S::TSNEVisualizations_Add),
            "TSNEVisualizations_Get" => ::std::option::Option::Some(S::TSNEVisualizations_Get),
            "Annotations_Add" => ::std::option::Option::Some(S::Annotations_Add),
            "Annotations_Get" => ::std::option::Option::Some(S::Annotations_Get),
            "Annotations_Patch" => ::std::option::Option::Some(S::Annotations_Patch),
            "Annotations_Delete" => ::std::option::Option::Some(S::Annotations_Delete),
            "Collectors_Add" => ::std::option::Option::Some(S::Collectors_Add),
            "Collectors_Get" => ::std::option::Option::Some(S::Collectors_Get),
            "Collectors_Delete" => ::std::option::Option::Some(S::Collectors_Delete),
            "Apps_Add" => ::std::option::Option::Some(S::Apps_Add),
            "Apps_Get" => ::std::option::Option::Some(S::Apps_Get),
            "Apps_Delete" => ::std::option::Option::Some(S::Apps_Delete),
            "Keys_Add" => ::std::option::Option::Some(S::Keys_Add),
            "Keys_Get" => ::std::option::Option::Some(S::Keys_Get),
            "Keys_Delete" => ::std::option::Option::Some(S::Keys_Delete),
            "Collaborators_Add" => ::std::option::Option::Some(S::Collaborators_Add),
            "Collaborators_Get" => ::std::option::Option::Some(S::Collaborators_Get),
            "Collaborators_Delete" => ::std::option::Option::Some(S::Collaborators_Delete),
            "Metrics_Add" => ::std::option::Option::Some(S::Metrics_Add),
            "Metrics_Get" => ::std::option::Option::Some(S::Metrics_Get),
            "Metrics_Delete" => ::std::option::Option::Some(S::Metrics_Delete),
            "Tasks_Add" => ::std::option::Option::Some(S::Tasks_Add),
            "Tasks_Get" => ::std::option::Option::Some(S::Tasks_Get),
            "Tasks_Delete" => ::std::option::Option::Some(S::Tasks_Delete),
            "PasswordPolicies_Add" => ::std::option::Option::Some(S::PasswordPolicies_Add),
            "PasswordPolicies_Get" => ::std::option::Option::Some(S::PasswordPolicies_Get),
            "PasswordPolicies_Delete" => ::std::option::Option::Some(S::PasswordPolicies_Delete),
            "LabelOrders_Get" => ::std::option::Option::Some(S::LabelOrders_Get),
            "LabelOrders_Add" => ::std::option::Option::Some(S::LabelOrders_Add),
            "LabelOrders_Delete" => ::std::option::Option::Some(S::LabelOrders_Delete),
            "UserFeatureConfigs_Get" => ::std::option::Option::Some(S::UserFeatureConfigs_Get),
            "FindDuplicateAnnotationsJobs_Add" => ::std::option::Option::Some(S::FindDuplicateAnnotationsJobs_Add),
            "FindDuplicateAnnotationsJobs_Get" => ::std::option::Option::Some(S::FindDuplicateAnnotationsJobs_Get),
            "FindDuplicateAnnotationsJobs_Delete" => ::std::option::Option::Some(S::FindDuplicateAnnotationsJobs_Delete),
            "Datasets_Get" => ::std::option::Option::Some(S::Datasets_Get),
            "Datasets_Add" => ::std::option::Option::Some(S::Datasets_Add),
            "Datasets_Delete" => ::std::option::Option::Some(S::Datasets_Delete),
            "Modules_Add" => ::std::option::Option::Some(S::Modules_Add),
            "Modules_Get" => ::std::option::Option::Some(S::Modules_Get),
            "Modules_Delete" => ::std::option::Option::Some(S::Modules_Delete),
            "InstalledModuleVersions_Add" => ::std::option::Option::Some(S::InstalledModuleVersions_Add),
            "InstalledModuleVersions_Get" => ::std::option::Option::Some(S::InstalledModuleVersions_Get),
            "InstalledModuleVersions_Delete" => ::std::option::Option::Some(S::InstalledModuleVersions_Delete),
            "Search" => ::std::option::Option::Some(S::Search),
            "SavedSearch_Get" => ::std::option::Option::Some(S::SavedSearch_Get),
            "SavedSearch_Add" => ::std::option::Option::Some(S::SavedSearch_Add),
            "SavedSearch_Delete" => ::std::option::Option::Some(S::SavedSearch_Delete),
            "ModelVersionPublications_Add" => ::std::option::Option::Some(S::ModelVersionPublications_Add),
            "ModelVersionPublications_Delete" => ::std::option::Option::Some(S::ModelVersionPublications_Delete),
            "WorkflowPublications_Add" => ::std::option::Option::Some(S::WorkflowPublications_Add),
            "WorkflowPublications_Delete" => ::std::option::Option::Some(S::WorkflowPublications_Delete),
            "BulkOperation_Add" => ::std::option::Option::Some(S::BulkOperation_Add),
            "BulkOperation_Get" => ::std::option::Option::Some(S::BulkOperation_Get),
            "BulkOperation_Delete" => ::std::option::Option::Some(S::BulkOperation_Delete),
            "HistoricalUsage_Get" => ::std::option::Option::Some(S::HistoricalUsage_Get),
            "Uploads_Get" => ::std::option::Option::Some(S::Uploads_Get),
            "Uploads_Add" => ::std::option::Option::Some(S::Uploads_Add),
            "Uploads_Delete" => ::std::option::Option::Some(S::Uploads_Delete),
            "Runners_Get" => ::std::option::Option::Some(S::Runners_Get),
            "Runners_Add" => ::std::option::Option::Some(S::Runners_Add),
            "Runners_Delete" => ::std::option::Option::Some(S::Runners_Delete),
            "RunnerItems_Get" => ::std::option::Option::Some(S::RunnerItems_Get),
            "RunnerItems_Add" => ::std::option::Option::Some(S::RunnerItems_Add),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [S] = &[
        S::undef,
        S::All,
        S::Predict,
        S::Inputs_Add,
        S::Inputs_Get,
        S::Inputs_Patch,
        S::Inputs_Delete,
        S::Outputs_Patch,
        S::Concepts_Add,
        S::Concepts_Get,
        S::Concepts_Patch,
        S::Concepts_Delete,
        S::Models_Add,
        S::Models_Get,
        S::Models_Patch,
        S::Models_Delete,
        S::Models_Train,
        S::Models_Sync,
        S::ModelExports_Get,
        S::ModelExports_Add,
        S::Workflows_Add,
        S::Workflows_Get,
        S::Workflows_Patch,
        S::Workflows_Delete,
        S::WorkflowMetrics_Get,
        S::WorkflowMetrics_Add,
        S::WorkflowMetrics_Delete,
        S::TSNEVisualizations_Add,
        S::TSNEVisualizations_Get,
        S::Annotations_Add,
        S::Annotations_Get,
        S::Annotations_Patch,
        S::Annotations_Delete,
        S::Collectors_Add,
        S::Collectors_Get,
        S::Collectors_Delete,
        S::Apps_Add,
        S::Apps_Get,
        S::Apps_Delete,
        S::Keys_Add,
        S::Keys_Get,
        S::Keys_Delete,
        S::Collaborators_Add,
        S::Collaborators_Get,
        S::Collaborators_Delete,
        S::Metrics_Add,
        S::Metrics_Get,
        S::Metrics_Delete,
        S::Tasks_Add,
        S::Tasks_Get,
        S::Tasks_Delete,
        S::PasswordPolicies_Add,
        S::PasswordPolicies_Get,
        S::PasswordPolicies_Delete,
        S::LabelOrders_Get,
        S::LabelOrders_Add,
        S::LabelOrders_Delete,
        S::UserFeatureConfigs_Get,
        S::FindDuplicateAnnotationsJobs_Add,
        S::FindDuplicateAnnotationsJobs_Get,
        S::FindDuplicateAnnotationsJobs_Delete,
        S::Datasets_Get,
        S::Datasets_Add,
        S::Datasets_Delete,
        S::Modules_Add,
        S::Modules_Get,
        S::Modules_Delete,
        S::InstalledModuleVersions_Add,
        S::InstalledModuleVersions_Get,
        S::InstalledModuleVersions_Delete,
        S::Search,
        S::SavedSearch_Get,
        S::SavedSearch_Add,
        S::SavedSearch_Delete,
        S::ModelVersionPublications_Add,
        S::ModelVersionPublications_Delete,
        S::WorkflowPublications_Add,
        S::WorkflowPublications_Delete,
        S::BulkOperation_Add,
        S::BulkOperation_Get,
        S::BulkOperation_Delete,
        S::HistoricalUsage_Get,
        S::Uploads_Get,
        S::Uploads_Add,
        S::Uploads_Delete,
        S::Runners_Get,
        S::Runners_Add,
        S::Runners_Delete,
        S::RunnerItems_Get,
        S::RunnerItems_Add,
    ];
}

impl ::protobuf::EnumFull for S {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("S").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            S::undef => 0,
            S::All => 1,
            S::Predict => 2,
            S::Inputs_Add => 3,
            S::Inputs_Get => 4,
            S::Inputs_Patch => 5,
            S::Inputs_Delete => 6,
            S::Outputs_Patch => 7,
            S::Concepts_Add => 8,
            S::Concepts_Get => 9,
            S::Concepts_Patch => 10,
            S::Concepts_Delete => 11,
            S::Models_Add => 12,
            S::Models_Get => 13,
            S::Models_Patch => 14,
            S::Models_Delete => 15,
            S::Models_Train => 16,
            S::Models_Sync => 17,
            S::ModelExports_Get => 18,
            S::ModelExports_Add => 19,
            S::Workflows_Add => 20,
            S::Workflows_Get => 21,
            S::Workflows_Patch => 22,
            S::Workflows_Delete => 23,
            S::WorkflowMetrics_Get => 24,
            S::WorkflowMetrics_Add => 25,
            S::WorkflowMetrics_Delete => 26,
            S::TSNEVisualizations_Add => 27,
            S::TSNEVisualizations_Get => 28,
            S::Annotations_Add => 29,
            S::Annotations_Get => 30,
            S::Annotations_Patch => 31,
            S::Annotations_Delete => 32,
            S::Collectors_Add => 33,
            S::Collectors_Get => 34,
            S::Collectors_Delete => 35,
            S::Apps_Add => 36,
            S::Apps_Get => 37,
            S::Apps_Delete => 38,
            S::Keys_Add => 39,
            S::Keys_Get => 40,
            S::Keys_Delete => 41,
            S::Collaborators_Add => 42,
            S::Collaborators_Get => 43,
            S::Collaborators_Delete => 44,
            S::Metrics_Add => 45,
            S::Metrics_Get => 46,
            S::Metrics_Delete => 47,
            S::Tasks_Add => 48,
            S::Tasks_Get => 49,
            S::Tasks_Delete => 50,
            S::PasswordPolicies_Add => 51,
            S::PasswordPolicies_Get => 52,
            S::PasswordPolicies_Delete => 53,
            S::LabelOrders_Get => 54,
            S::LabelOrders_Add => 55,
            S::LabelOrders_Delete => 56,
            S::UserFeatureConfigs_Get => 57,
            S::FindDuplicateAnnotationsJobs_Add => 58,
            S::FindDuplicateAnnotationsJobs_Get => 59,
            S::FindDuplicateAnnotationsJobs_Delete => 60,
            S::Datasets_Get => 61,
            S::Datasets_Add => 62,
            S::Datasets_Delete => 63,
            S::Modules_Add => 64,
            S::Modules_Get => 65,
            S::Modules_Delete => 66,
            S::InstalledModuleVersions_Add => 67,
            S::InstalledModuleVersions_Get => 68,
            S::InstalledModuleVersions_Delete => 69,
            S::Search => 70,
            S::SavedSearch_Get => 71,
            S::SavedSearch_Add => 72,
            S::SavedSearch_Delete => 73,
            S::ModelVersionPublications_Add => 74,
            S::ModelVersionPublications_Delete => 75,
            S::WorkflowPublications_Add => 76,
            S::WorkflowPublications_Delete => 77,
            S::BulkOperation_Add => 78,
            S::BulkOperation_Get => 79,
            S::BulkOperation_Delete => 80,
            S::HistoricalUsage_Get => 81,
            S::Uploads_Get => 82,
            S::Uploads_Add => 83,
            S::Uploads_Delete => 84,
            S::Runners_Get => 85,
            S::Runners_Add => 86,
            S::Runners_Delete => 87,
            S::RunnerItems_Get => 88,
            S::RunnerItems_Add => 89,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for S {
    fn default() -> Self {
        S::undef
    }
}

impl S {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<S>("S")
    }
}

/// Extension fields
pub mod exts {

    pub const clarfai_exposed: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(80318, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const clarifai_depending_scopes: ::protobuf::ext::ExtFieldRepeated<::protobuf::descriptor::EnumValueOptions, ::protobuf::EnumOrUnknown<super::S>> = ::protobuf::ext::ExtFieldRepeated::new(80319, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_ENUM);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n%proto/clarifai/auth/scope/scope.proto\x12\x13clarifai.auth.scope\x1a\
    \x20google/protobuf/descriptor.proto\"Y\n\tScopeList\x12.\n\x06scopes\
    \x18\x01\x20\x03(\x0e2\x16.clarifai.auth.scope.SR\x06scopes\x12\x1c\n\te\
    ndpoints\x18\x02\x20\x03(\tR\tendpoints*\xbc\x16\n\x01S\x12\t\n\x05undef\
    \x10\0\x12\r\n\x03All\x10\x01\x1a\x04\xf0\x9b'\x01\x12\x11\n\x07Predict\
    \x10\x02\x1a\x04\xf0\x9b'\x01\x12\x18\n\nInputs_Add\x10\x04\x1a\x08\xf0\
    \x9b'\x01\xf8\x9b'\x05\x12\x14\n\nInputs_Get\x10\x05\x1a\x04\xf0\x9b'\
    \x01\x12\x20\n\x0cInputs_Patch\x10\x07\x1a\x0e\x08\x01\xf0\x9b'\x01\xf8\
    \x9b'\x04\xf8\x9b'\x05\x12\x1f\n\rInputs_Delete\x10\x08\x1a\x0c\xf0\x9b'\
    \x01\xf8\x9b'\x04\xf8\x9b'\x05\x12\x1d\n\rOutputs_Patch\x10\t\x1a\n\x08\
    \x01\xf8\x9b'\x05\xf8\x9b'\x02\x12\x1a\n\x0cConcepts_Add\x10\n\x1a\x08\
    \xf0\x9b'\x01\xf8\x9b'\x0b\x12\x16\n\x0cConcepts_Get\x10\x0b\x1a\x04\xf0\
    \x9b'\x01\x12\"\n\x0eConcepts_Patch\x10\x0c\x1a\x0e\x08\x01\xf0\x9b'\x01\
    \xf8\x9b'\n\xf8\x9b'\x0b\x12\x1d\n\x0fConcepts_Delete\x10\r\x1a\x08\xf8\
    \x9b'\n\xf8\x9b'\x0b\x12\x18\n\nModels_Add\x10\x0e\x1a\x08\xf0\x9b'\x01\
    \xf8\x9b'\x0f\x12\x14\n\nModels_Get\x10\x0f\x1a\x04\xf0\x9b'\x01\x12$\n\
    \x0cModels_Patch\x10\x10\x1a\x12\x08\x01\xf0\x9b'\x01\xf8\x9b'\x0e\xf8\
    \x9b'\x0f\xf8\x9b'\x1a\x12\x1f\n\rModels_Delete\x10\x11\x1a\x0c\xf0\x9b'\
    \x01\xf8\x9b'\x0e\xf8\x9b'\x0f\x12\x1a\n\x0cModels_Train\x10\x1a\x1a\x08\
    \xf0\x9b'\x01\xf8\x9b'\x0f\x12\x15\n\x0bModels_Sync\x10\x1b\x1a\x04\xf8\
    \x9b'\x0f\x12\x1b\n\x10ModelExports_Get\x10\x8e\x01\x1a\x04\xf0\x9b'\x01\
    \x12\x20\n\x10ModelExports_Add\x10\x8f\x01\x1a\t\xf0\x9b'\x01\xf8\x9b'\
    \x8e\x01\x12\x1b\n\rWorkflows_Add\x10\x12\x1a\x08\xf0\x9b'\x01\xf8\x9b'\
    \x13\x12\x17\n\rWorkflows_Get\x10\x13\x1a\x04\xf0\x9b'\x01\x12#\n\x0fWor\
    kflows_Patch\x10\x14\x1a\x0e\x08\x01\xf0\x9b'\x01\xf8\x9b'\x12\xf8\x9b'\
    \x13\x12\"\n\x10Workflows_Delete\x10\x15\x1a\x0c\xf0\x9b'\x01\xf8\x9b'\
    \x12\xf8\x9b'\x13\x12\x1d\n\x13WorkflowMetrics_Get\x10`\x1a\x04\xf0\x9b'\
    \x01\x12!\n\x13WorkflowMetrics_Add\x10a\x1a\x08\xf0\x9b'\x01\xf8\x9b'`\
    \x12(\n\x16WorkflowMetrics_Delete\x10b\x1a\x0c\xf0\x9b'\x01\xf8\x9b'a\
    \xf8\x9b'`\x12\"\n\x16TSNEVisualizations_Add\x10\x18\x1a\x06\x08\x01\xf8\
    \x9b'\x19\x12\x1e\n\x16TSNEVisualizations_Get\x10\x19\x1a\x02\x08\x01\
    \x12\x1d\n\x0fAnnotations_Add\x10%\x1a\x08\xf0\x9b'\x01\xf8\x9b'&\x12\
    \x19\n\x0fAnnotations_Get\x10&\x1a\x04\xf0\x9b'\x01\x12%\n\x11Annotation\
    s_Patch\x10'\x1a\x0e\x08\x01\xf0\x9b'\x01\xf8\x9b'%\xf8\x9b'&\x12$\n\x12\
    Annotations_Delete\x10(\x1a\x0c\xf0\x9b'\x01\xf8\x9b'%\xf8\x9b'&\x12\x1c\
    \n\x0eCollectors_Add\x10)\x1a\x08\xf0\x9b'\x01\xf8\x9b'*\x12\x18\n\x0eCo\
    llectors_Get\x10*\x1a\x04\xf0\x9b'\x01\x12#\n\x11Collectors_Delete\x10+\
    \x1a\x0c\xf0\x9b'\x01\xf8\x9b')\xf8\x9b'*\x12\x16\n\x08Apps_Add\x10,\x1a\
    \x08\xf0\x9b'\x01\xf8\x9b'-\x12\x12\n\x08Apps_Get\x10-\x1a\x04\xf0\x9b'\
    \x01\x12\x1d\n\x0bApps_Delete\x10.\x1a\x0c\xf0\x9b'\x01\xf8\x9b',\xf8\
    \x9b'-\x12\x16\n\x08Keys_Add\x10/\x1a\x08\xf0\x9b'\x01\xf8\x9b'0\x12\x12\
    \n\x08Keys_Get\x100\x1a\x04\xf0\x9b'\x01\x12\x1d\n\x0bKeys_Delete\x101\
    \x1a\x0c\xf0\x9b'\x01\xf8\x9b'/\xf8\x9b'0\x12\x1f\n\x11Collaborators_Add\
    \x103\x1a\x08\xf0\x9b'\x01\xf8\x9b'2\x12\x1b\n\x11Collaborators_Get\x102\
    \x1a\x04\xf0\x9b'\x01\x12&\n\x14Collaborators_Delete\x104\x1a\x0c\xf0\
    \x9b'\x01\xf8\x9b'3\xf8\x9b'2\x12\x19\n\x0bMetrics_Add\x106\x1a\x08\xf0\
    \x9b'\x01\xf8\x9b'5\x12\x15\n\x0bMetrics_Get\x105\x1a\x04\xf0\x9b'\x01\
    \x12\x20\n\x0eMetrics_Delete\x10?\x1a\x0c\xf0\x9b'\x01\xf8\x9b'6\xf8\x9b\
    '5\x12\x17\n\tTasks_Add\x107\x1a\x08\xf0\x9b'\x01\xf8\x9b'8\x12\x13\n\tT\
    asks_Get\x108\x1a\x04\xf0\x9b'\x01\x12\x1e\n\x0cTasks_Delete\x10F\x1a\
    \x0c\xf0\x9b'\x01\xf8\x9b'7\xf8\x9b'8\x12\"\n\x14PasswordPolicies_Add\
    \x109\x1a\x08\xf0\x9b'\x01\xf8\x9b':\x12\x1e\n\x14PasswordPolicies_Get\
    \x10:\x1a\x04\xf0\x9b'\x01\x12)\n\x17PasswordPolicies_Delete\x10;\x1a\
    \x0c\xf0\x9b'\x01\xf8\x9b'9\xf8\x9b':\x12\x19\n\x0fLabelOrders_Get\x10C\
    \x1a\x04\xf0\x9b'\x01\x12\x1d\n\x0fLabelOrders_Add\x10D\x1a\x08\xf0\x9b'\
    \x01\xf8\x9b'C\x12$\n\x12LabelOrders_Delete\x10E\x1a\x0c\xf0\x9b'\x01\
    \xf8\x9b'D\xf8\x9b'C\x12\x20\n\x16UserFeatureConfigs_Get\x10G\x1a\x04\
    \xf0\x9b'\x01\x12.\n\x20FindDuplicateAnnotationsJobs_Add\x10f\x1a\x08\
    \xf0\x9b'\x01\xf8\x9b'g\x12*\n\x20FindDuplicateAnnotationsJobs_Get\x10g\
    \x1a\x04\xf0\x9b'\x01\x125\n#FindDuplicateAnnotationsJobs_Delete\x10h\
    \x1a\x0c\xf0\x9b'\x01\xf8\x9b'f\xf8\x9b'g\x12\x16\n\x0cDatasets_Get\x10i\
    \x1a\x04\xf0\x9b'\x01\x12\x1a\n\x0cDatasets_Add\x10j\x1a\x08\xf0\x9b'\
    \x01\xf8\x9b'i\x12!\n\x0fDatasets_Delete\x10k\x1a\x0c\xf0\x9b'\x01\xf8\
    \x9b'i\xf8\x9b'j\x12\x19\n\x0bModules_Add\x10l\x1a\x08\xf0\x9b'\x01\xf8\
    \x9b'm\x12\x15\n\x0bModules_Get\x10m\x1a\x04\xf0\x9b'\x01\x12\x20\n\x0eM\
    odules_Delete\x10n\x1a\x0c\xf0\x9b'\x01\xf8\x9b'l\xf8\x9b'm\x12-\n\x1bIn\
    stalledModuleVersions_Add\x10o\x1a\x0c\xf0\x9b'\x01\xf8\x9b'p\xf8\x9b'm\
    \x12)\n\x1bInstalledModuleVersions_Get\x10p\x1a\x08\xf0\x9b'\x01\xf8\x9b\
    'm\x124\n\x1eInstalledModuleVersions_Delete\x10q\x1a\x10\xf0\x9b'\x01\
    \xf8\x9b'o\xf8\x9b'p\xf8\x9b'm\x12\x10\n\x06Search\x10\x03\x1a\x04\xf0\
    \x9b'\x01\x12\x19\n\x0fSavedSearch_Get\x10r\x1a\x04\xf0\x9b'\x01\x12\x1d\
    \n\x0fSavedSearch_Add\x10s\x1a\x08\xf0\x9b'\x01\xf8\x9b'r\x12$\n\x12Save\
    dSearch_Delete\x10t\x1a\x0c\xf0\x9b'\x01\xf8\x9b'r\xf8\x9b's\x12&\n\x1cM\
    odelVersionPublications_Add\x10u\x1a\x04\xf0\x9b'\x01\x12)\n\x1fModelVer\
    sionPublications_Delete\x10v\x1a\x04\xf0\x9b'\x01\x12\"\n\x18WorkflowPub\
    lications_Add\x10w\x1a\x04\xf0\x9b'\x01\x12%\n\x1bWorkflowPublications_D\
    elete\x10x\x1a\x04\xf0\x9b'\x01\x12\x1f\n\x11BulkOperation_Add\x10y\x1a\
    \x08\xf0\x9b'\x01\xf8\x9b'z\x12\x1b\n\x11BulkOperation_Get\x10z\x1a\x04\
    \xf0\x9b'\x01\x12&\n\x14BulkOperation_Delete\x10{\x1a\x0c\xf0\x9b'\x01\
    \xf8\x9b'y\xf8\x9b'z\x12\x17\n\x13HistoricalUsage_Get\x10|\x12\x16\n\x0b\
    Uploads_Get\x10\x80\x01\x1a\x04\xf0\x9b'\x01\x12\x1b\n\x0bUploads_Add\
    \x10\x81\x01\x1a\t\xf0\x9b'\x01\xf8\x9b'\x80\x01\x12#\n\x0eUploads_Delet\
    e\x10\x82\x01\x1a\x0e\xf0\x9b'\x01\xf8\x9b'\x80\x01\xf8\x9b'\x81\x01\x12\
    \x16\n\x0bRunners_Get\x10\x83\x01\x1a\x04\xf0\x9b'\x01\x12\x1b\n\x0bRunn\
    ers_Add\x10\x84\x01\x1a\t\xf0\x9b'\x01\xf8\x9b'\x83\x01\x12#\n\x0eRunner\
    s_Delete\x10\x85\x01\x1a\x0e\xf0\x9b'\x01\xf8\x9b'\x83\x01\xf8\x9b'\x84\
    \x01\x12\x1a\n\x0fRunnerItems_Get\x10\x86\x01\x1a\x04\xf0\x9b'\x01\x12\
    \x1f\n\x0fRunnerItems_Add\x10\x87\x01\x1a\t\xf0\x9b'\x01\xf8\x9b'\x86\
    \x01\"\x04\x08\x1e\x10\x1e\"\x04\x08\x1f\x10\x1f\"\x04\x08\x20\x10\x20\"\
    \x04\x08!\x10!\"\x04\x08\"\x10\"\"\x04\x08}\x10}\"\x04\x08~\x10~:L\n\x0f\
    clarfai_exposed\x18\xbe\xf3\x04\x20\x01(\x08\x12!.google.protobuf.EnumVa\
    lueOptionsR\x0eclarfaiExposed:w\n\x19clarifai_depending_scopes\x18\xbf\
    \xf3\x04\x20\x03(\x0e2\x16.clarifai.auth.scope.S\x12!.google.protobuf.En\
    umValueOptionsR\x17clarifaiDependingScopesBg\n\x1ccom.clarifai.grpc.auth\
    .scopeP\x01Z>github.com/Clarifai/clarifai-go-grpc/proto/clarifai/auth/sc\
    ope\xa2\x02\x04CAIPJ\xc9r\n\x07\x12\x05\0\0\xca\x03\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\t\n\x02\x03\0\x12\x03\x02\0*\n\x08\n\x01\x02\x12\x03\
    \x04\0\x1c\n\x08\n\x01\x08\x12\x03\x06\0U\n\t\n\x02\x08\x0b\x12\x03\x06\
    \0U\n\x08\n\x01\x08\x12\x03\x07\0\"\n\t\n\x02\x08\n\x12\x03\x07\0\"\n\
    \x08\n\x01\x08\x12\x03\x08\05\n\t\n\x02\x08\x01\x12\x03\x08\05\n\x08\n\
    \x01\x08\x12\x03\t\0\"\n\t\n\x02\x08$\x12\x03\t\0\"\n\n\n\x02\x04\0\x12\
    \x04\x0c\0\x11\x01\n\n\n\x03\x04\0\x01\x12\x03\x0c\x08\x11\nS\n\x04\x04\
    \0\x02\0\x12\x03\x0e\x02\x18\x1aF\x20These\x20are\x20the\x20list\x20of\
    \x20low-level\x20scopes\x20to\x20check\x20from\x20the\x20enum\x20below.\
    \n\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x0e\x02\n\n\x0c\n\x05\x04\0\x02\0\
    \x06\x12\x03\x0e\x0b\x0c\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x0e\r\x13\n\
    \x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0e\x16\x17\nE\n\x04\x04\0\x02\x01\
    \x12\x03\x10\x02\x20\x1a8\x20This\x20is\x20a\x20list\x20of\x20fully\x20q\
    ualified\x20grpc\x20names\x20to\x20check.\n\n\x0c\n\x05\x04\0\x02\x01\
    \x04\x12\x03\x10\x02\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x10\x0b\x11\
    \n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x10\x12\x1b\n\x0c\n\x05\x04\0\x02\
    \x01\x03\x12\x03\x10\x1e\x1f\n\xce\x0c\n\x02\x05\0\x12\x05/\0\xc1\x03\
    \x01\x1a\xc0\x0c\x20Next\x20index:\x2041\n\x20NOTE:\x20When\x20updating\
    \x20the\x20list\x20of\x20\"clarifai_exposed\"\x20scopes,\x20please\x20al\
    so\n\x20update\x20the\x20TestScopes\x20function\x20in\x20main_key_test.g\
    o\x20and\x20TestGetExposedScopes\x20function\x20in\n\x20scope_test.go\n\
    \n\x20The\x20dependencies\x20listed\x20for\x20each\x20scope\x20are\x20si\
    mply\x20recommendations\x20so\x20that\x20a\x20user\n\x20cannot\x20make\
    \x20a\x20key\x20that\x20would\x20be\x20useless.\x20Beyond\x20the\x20key\
    \x20creation\x20they\x20are\x20not\x20enforced\n\x20but\x20rather\x20the\
    \x20scopes\x20are\x20enforce\x20when\x20data\x20is\x20accessed.\n\n\n\
    \x20There\x20is\x20the\x20following\x20conventions\x20in\x20place,\x20ma\
    ke\x20sure\x20you\x20add\x20them\x20to\x20the\x20scopes\x20for\x20all\
    \x20new\n\x20resource\x20types:\n\n\x201.\x20*_Add\x20requires\x20the\
    \x20corresponding\x20_Get.\n\x202.\x20*_Delete\x20requires\x20the\x20cor\
    responding\x20_Add\x20and\x20_Get.\n\x203.\x20*_Patch\x20is\x20deprecate\
    d\x20and\x20not\x20check\x20anywhere.\n\n\x20Think\x20of\x20the\x20depen\
    dencies\x20in\x20this\x20file\x20at\x20the\x20DB\x20level.\x20If\x20you\
    \x20cannot\x20make\x20a\x20DB\x20call\x20to\x20Get,\x20Add\n\x20or\x20De\
    lete\x20a\x20resource\x20without\x20having\x20access\x20to\x20another\
    \x20resource\x20then\x20you\x20should\x20add\x20it\x20here.\x20That\n\
    \x20should\x20for\x20the\x20most\x20part\x20be\x20the\x20same\x20resourc\
    e\x20type.\x20In\x20service.proto\x20for\x20the\x20API\x20level\x20you\
    \x20will\n\x20also\x20specify\x20cl_depending_scopes\x20for\x20each\x20A\
    PI\x20endpoint.\x20Those\x20cover\x20cases\x20where\x20an\x20endpoint\n\
    \x20might\x20need\x20to\x20access\x20more\x20than\x20just\x20that\x20one\
    \x20resource\x20type\x20in\x20order\x20to\x20operate\x20(ie.\x20API\x20h\
    andlers\n\x20that\x20make\x20multiple\x20DB\x20calls\x20of\x20various\
    \x20resource\x20types\x20likely\x20have\x20more\x20cl_depending_scopes\
    \x20than\n\x20the\x20ones\x20listed\x20below).\x20For\x20example:\x20Pos\
    tCollectors\x20to\x20create\x20a\x20collector\x20we\x20make\x20sure\x20t\
    hat\x20you\n\x20can\x20do\x20model\x20predictions,\x20get\x20concepts,\
    \x20etc.\x20so\x20that\x20you\x20don't\x20have\x20a\x20collector\x20that\
    \x20would\x20be\n\x20useless\x20at\x20the\x20end\x20of\x20that\x20API\
    \x20handler\x20but\x20below\x20you\x20can\x20see\x20that\x20the\x20depen\
    dencies\x20of\x20Collector\n\x20scopes\x20are\x20only\x20on\x20other\x20\
    Collector\x20scopes.\n\n\n\n\n\x03\x05\0\x01\x12\x03/\x05\x06\n\n\n\x03\
    \x05\0\x04\x12\x030\x02(\n\x0b\n\x04\x05\0\x04\0\x12\x030\x0b\r\n\x0c\n\
    \x05\x05\0\x04\0\x01\x12\x030\x0b\r\n\x0c\n\x05\x05\0\x04\0\x02\x12\x030\
    \x0b\r\n\x0b\n\x04\x05\0\x04\x01\x12\x030\x0f\x11\n\x0c\n\x05\x05\0\x04\
    \x01\x01\x12\x030\x0f\x11\n\x0c\n\x05\x05\0\x04\x01\x02\x12\x030\x0f\x11\
    \n\x0b\n\x04\x05\0\x04\x02\x12\x030\x13\x15\n\x0c\n\x05\x05\0\x04\x02\
    \x01\x12\x030\x13\x15\n\x0c\n\x05\x05\0\x04\x02\x02\x12\x030\x13\x15\n\
    \x0b\n\x04\x05\0\x04\x03\x12\x030\x17\x19\n\x0c\n\x05\x05\0\x04\x03\x01\
    \x12\x030\x17\x19\n\x0c\n\x05\x05\0\x04\x03\x02\x12\x030\x17\x19\n\x0b\n\
    \x04\x05\0\x04\x04\x12\x030\x1b\x1d\n\x0c\n\x05\x05\0\x04\x04\x01\x12\
    \x030\x1b\x1d\n\x0c\n\x05\x05\0\x04\x04\x02\x12\x030\x1b\x1d\n\x0b\n\x04\
    \x05\0\x04\x05\x12\x030\x1f\"\n\x0c\n\x05\x05\0\x04\x05\x01\x12\x030\x1f\
    \"\n\x0c\n\x05\x05\0\x04\x05\x02\x12\x030\x1f\"\n\x0b\n\x04\x05\0\x04\
    \x06\x12\x030$'\n\x0c\n\x05\x05\0\x04\x06\x01\x12\x030$'\n\x0c\n\x05\x05\
    \0\x04\x06\x02\x12\x030$'\n\xcb\x01\n\x04\x05\0\x02\0\x12\x034\x02\x0c\
    \x1a\xbd\x01\x20introduce\x20undef\x20so\x20that\x20the\x20zero\x20(defa\
    ult/unset)\x20value\x20of\x20the\x20enum\x20is\x20not\x20a\x20real\n\x20\
    permission.\x20\x20undef\x20is\x20only\x20present\x20for\x20this\x20purp\
    ose\x20and\x20should\x20not\x20be\x20used\n\x20to\x20indicate\x20any\x20\
    \"real\"\x20value.\n\n\x0c\n\x05\x05\0\x02\0\x01\x12\x034\x02\x07\n\x0c\
    \n\x05\x05\0\x02\0\x02\x12\x034\n\x0b\n\x0b\n\x04\x05\0\x02\x01\x12\x036\
    \x02%\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x036\x02\x05\n\x0c\n\x05\x05\0\
    \x02\x01\x02\x12\x036\x08\t\n\x0c\n\x05\x05\0\x02\x01\x03\x12\x036\n$\n\
    \x0f\n\x08\x05\0\x02\x01\x03\xbe\xf3\x04\x12\x036\x0b#\n6\n\x04\x05\0\
    \x02\x02\x12\x039\x02)\x1a)\x20Make\x20an\x20rpc\x20to\x20our\x20predict\
    ion\x20services.\n\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x039\x02\t\n\x0c\n\
    \x05\x05\0\x02\x02\x02\x12\x039\x0c\r\n\x0c\n\x05\x05\0\x02\x02\x03\x12\
    \x039\x0e(\n\x0f\n\x08\x05\0\x02\x02\x03\xbe\xf3\x04\x12\x039\x0f'\n4\n\
    \x04\x05\0\x02\x03\x12\x04<\x02=<\x1a&\x20Write\x20to\x20the\x20inputs\
    \x20table\x20in\x20the\x20DB.\n\n\x0c\n\x05\x05\0\x02\x03\x01\x12\x03<\
    \x02\x0c\n\x0c\n\x05\x05\0\x02\x03\x02\x12\x03<\x0f\x10\n\r\n\x05\x05\0\
    \x02\x03\x03\x12\x04<\x11=;\n\x0f\n\x08\x05\0\x02\x03\x03\xbe\xf3\x04\
    \x12\x03<\x12*\n\x10\n\t\x05\0\x02\x03\x03\xbf\xf3\x04\0\x12\x03=\x12:\n\
    4\n\x04\x05\0\x02\x04\x12\x03?\x02,\x1a'\x20Read\x20from\x20the\x20input\
    s\x20table\x20in\x20the\x20DB.\n\n\x0c\n\x05\x05\0\x02\x04\x01\x12\x03?\
    \x02\x0c\n\x0c\n\x05\x05\0\x02\x04\x02\x12\x03?\x0f\x10\n\x0c\n\x05\x05\
    \0\x02\x04\x03\x12\x03?\x11+\n\x0f\n\x08\x05\0\x02\x04\x03\xbe\xf3\x04\
    \x12\x03?\x12*\nY\n\x04\x05\0\x02\x05\x12\x04C\x02F'\x1aK\x20To\x20patch\
    \x20we\x20need\x20read/write.\n\x20Deprecated.\n\x20Optionally\x20needs\
    \x20Concepts_Add.\n\n\x0c\n\x05\x05\0\x02\x05\x01\x12\x03C\x02\x0e\n\x0c\
    \n\x05\x05\0\x02\x05\x02\x12\x03C\x11\x12\n\r\n\x05\x05\0\x02\x05\x03\
    \x12\x04C\x13F&\n\x0f\n\x08\x05\0\x02\x05\x03\xbe\xf3\x04\x12\x03C\x14,\
    \n\x10\n\t\x05\0\x02\x05\x03\xbf\xf3\x04\0\x12\x03D\x14<\n\x10\n\t\x05\0\
    \x02\x05\x03\xbf\xf3\x04\x01\x12\x03E\x14<\n\r\n\x06\x05\0\x02\x05\x03\
    \x01\x12\x03F\x14%\n,\n\x04\x05\0\x02\x06\x12\x04I\x02K?\x1a\x1e\x20To\
    \x20delete\x20we\x20need\x20read/write\n\n\x0c\n\x05\x05\0\x02\x06\x01\
    \x12\x03I\x02\x0f\n\x0c\n\x05\x05\0\x02\x06\x02\x12\x03I\x12\x13\n\r\n\
    \x05\x05\0\x02\x06\x03\x12\x04I\x14K>\n\x0f\n\x08\x05\0\x02\x06\x03\xbe\
    \xf3\x04\x12\x03I\x15-\n\x10\n\t\x05\0\x02\x06\x03\xbf\xf3\x04\0\x12\x03\
    J\x15=\n\x10\n\t\x05\0\x02\x06\x03\xbf\xf3\x04\x01\x12\x03K\x15=\n\x1b\n\
    \x04\x05\0\x02\x07\x12\x04M\x02O(\x1a\r\x20Deprecated.\n\n\x0c\n\x05\x05\
    \0\x02\x07\x01\x12\x03M\x02\x0f\n\x0c\n\x05\x05\0\x02\x07\x02\x12\x03M\
    \x12\x13\n\r\n\x05\x05\0\x02\x07\x03\x12\x04M\x14O'\n\x10\n\t\x05\0\x02\
    \x07\x03\xbf\xf3\x04\0\x12\x03M\x15=\n\x10\n\t\x05\0\x02\x07\x03\xbf\xf3\
    \x04\x01\x12\x03N\x15:\n\r\n\x06\x05\0\x02\x07\x03\x01\x12\x03O\x15&\n0\
    \n\x04\x05\0\x02\x08\x12\x04R\x02S@\x1a\"\x20Write\x20to\x20the\x20conce\
    pts\x20DB\x20tables.\n\n\x0c\n\x05\x05\0\x02\x08\x01\x12\x03R\x02\x0e\n\
    \x0c\n\x05\x05\0\x02\x08\x02\x12\x03R\x11\x13\n\r\n\x05\x05\0\x02\x08\
    \x03\x12\x04R\x14S?\n\x0f\n\x08\x05\0\x02\x08\x03\xbe\xf3\x04\x12\x03R\
    \x15-\n\x10\n\t\x05\0\x02\x08\x03\xbf\xf3\x04\0\x12\x03S\x14>\n0\n\x04\
    \x05\0\x02\t\x12\x03V\x02/\x1a#\x20Read\x20from\x20the\x20concepts\x20DB\
    \x20tables.\n\n\x0c\n\x05\x05\0\x02\t\x01\x12\x03V\x02\x0e\n\x0c\n\x05\
    \x05\0\x02\t\x02\x12\x03V\x11\x13\n\x0c\n\x05\x05\0\x02\t\x03\x12\x03V\
    \x14.\n\x0f\n\x08\x05\0\x02\t\x03\xbe\xf3\x04\x12\x03V\x15-\n\\\n\x04\
    \x05\0\x02\n\x12\x04\\\x02_*\x1a*\x20To\x20patch\x20we\x20need\x20read/w\
    rite.\n\x20Deprecated\n2\"\x20TODO:\x20No\x20concept\x20searches\x20scop\
    e.\n\n\x0c\n\x05\x05\0\x02\n\x01\x12\x03\\\x02\x10\n\x0c\n\x05\x05\0\x02\
    \n\x02\x12\x03\\\x13\x15\n\r\n\x05\x05\0\x02\n\x03\x12\x04\\\x16_)\n\x0f\
    \n\x08\x05\0\x02\n\x03\xbe\xf3\x04\x12\x03\\\x17/\n\x10\n\t\x05\0\x02\n\
    \x03\xbf\xf3\x04\0\x12\x03]\x17A\n\x10\n\t\x05\0\x02\n\x03\xbf\xf3\x04\
    \x01\x12\x03^\x17A\n\r\n\x06\x05\0\x02\n\x03\x01\x12\x03_\x17(\nE\n\x04\
    \x05\0\x02\x0b\x12\x04c\x02dD\x1a7\x20To\x20delete\x20we\x20need\x20read\
    /write.\n\x20Note:\x20not\x20implemented.\n\n\x0c\n\x05\x05\0\x02\x0b\
    \x01\x12\x03c\x02\x11\n\x0c\n\x05\x05\0\x02\x0b\x02\x12\x03c\x14\x16\n\r\
    \n\x05\x05\0\x02\x0b\x03\x12\x04c\x17dC\n\x10\n\t\x05\0\x02\x0b\x03\xbf\
    \xf3\x04\0\x12\x03c\x18B\n\x10\n\t\x05\0\x02\x0b\x03\xbf\xf3\x04\x01\x12\
    \x03d\x18B\n.\n\x04\x05\0\x02\x0c\x12\x04g\x02h=\x1a\x20\x20Write\x20to\
    \x20the\x20models\x20DB\x20tables.\n\n\x0c\n\x05\x05\0\x02\x0c\x01\x12\
    \x03g\x02\x0c\n\x0c\n\x05\x05\0\x02\x0c\x02\x12\x03g\x0f\x11\n\r\n\x05\
    \x05\0\x02\x0c\x03\x12\x04g\x12h<\n\x0f\n\x08\x05\0\x02\x0c\x03\xbe\xf3\
    \x04\x12\x03g\x13+\n\x10\n\t\x05\0\x02\x0c\x03\xbf\xf3\x04\0\x12\x03h\
    \x13;\nB\n\x04\x05\0\x02\r\x12\x03k\x02-\x1a5\x20Read\x20from\x20the\x20\
    models\x20and\x20models\x20versions\x20DB\x20tables.\n\n\x0c\n\x05\x05\0\
    \x02\r\x01\x12\x03k\x02\x0c\n\x0c\n\x05\x05\0\x02\r\x02\x12\x03k\x0f\x11\
    \n\x0c\n\x05\x05\0\x02\r\x03\x12\x03k\x12,\n\x0f\n\x08\x05\0\x02\r\x03\
    \xbe\xf3\x04\x12\x03k\x13+\n9\n\x04\x05\0\x02\x0e\x12\x04o\x02s(\x1a+\
    \x20To\x20patch\x20we\x20need\x20read/write.\n\x20Deprecated.\n\n\x0c\n\
    \x05\x05\0\x02\x0e\x01\x12\x03o\x02\x0e\n\x0c\n\x05\x05\0\x02\x0e\x02\
    \x12\x03o\x11\x13\n\r\n\x05\x05\0\x02\x0e\x03\x12\x04o\x14s'\n\x0f\n\x08\
    \x05\0\x02\x0e\x03\xbe\xf3\x04\x12\x03o\x15-\n\x10\n\t\x05\0\x02\x0e\x03\
    \xbf\xf3\x04\0\x12\x03p\x15=\n\x10\n\t\x05\0\x02\x0e\x03\xbf\xf3\x04\x01\
    \x12\x03q\x15=\n\x10\n\t\x05\0\x02\x0e\x03\xbf\xf3\x04\x02\x12\x03r\x15?\
    \n\r\n\x06\x05\0\x02\x0e\x03\x01\x12\x03s\x15&\n-\n\x04\x05\0\x02\x0f\
    \x12\x04v\x02x@\x1a\x1f\x20To\x20delete\x20we\x20need\x20read/write.\n\n\
    \x0c\n\x05\x05\0\x02\x0f\x01\x12\x03v\x02\x0f\n\x0c\n\x05\x05\0\x02\x0f\
    \x02\x12\x03v\x12\x14\n\r\n\x05\x05\0\x02\x0f\x03\x12\x04v\x15x?\n\x0f\n\
    \x08\x05\0\x02\x0f\x03\xbe\xf3\x04\x12\x03v\x16.\n\x10\n\t\x05\0\x02\x0f\
    \x03\xbf\xf3\x04\0\x12\x03w\x16>\n\x10\n\t\x05\0\x02\x0f\x03\xbf\xf3\x04\
    \x01\x12\x03x\x16>\n\xc3\x01\n\x04\x05\0\x02\x10\x12\x04}\x02~?\x1a\xb4\
    \x01\x20Note:\x20Models_Train\x20is\x20effectively\x20doing\x20POST\x20/\
    models/{models_id}/versions\x20so\x20it's\x20treated\x20that\n\x20way\
    \x20in\x20terms\x20of\x20data\x20access\x20under\x20the\x20hood.\n\x20Wr\
    ite\x20to\x20the\x20model\x20versions\x20DB\x20table.\n\n\x0c\n\x05\x05\
    \0\x02\x10\x01\x12\x03}\x02\x0e\n\x0c\n\x05\x05\0\x02\x10\x02\x12\x03}\
    \x11\x13\n\r\n\x05\x05\0\x02\x10\x03\x12\x04}\x14~>\n\x0f\n\x08\x05\0\
    \x02\x10\x03\xbe\xf3\x04\x12\x03}\x15-\n\x10\n\t\x05\0\x02\x10\x03\xbf\
    \xf3\x04\0\x12\x03~\x15=\n,\n\x04\x05\0\x02\x11\x12\x04\x81\x01\x02>\x1a\
    \x1e\x20Internal\x20only\x20model\x20syncing.\n\n\r\n\x05\x05\0\x02\x11\
    \x01\x12\x04\x81\x01\x02\r\n\r\n\x05\x05\0\x02\x11\x02\x12\x04\x81\x01\
    \x10\x12\n\r\n\x05\x05\0\x02\x11\x03\x12\x04\x81\x01\x13=\n\x11\n\t\x05\
    \0\x02\x11\x03\xbf\xf3\x04\0\x12\x04\x81\x01\x14<\n+\n\x04\x05\0\x02\x12\
    \x12\x04\x84\x01\x024\x1a\x1d\x20To\x20get\x20model\x20version\x20export\
    \n\n\r\n\x05\x05\0\x02\x12\x01\x12\x04\x84\x01\x02\x12\n\r\n\x05\x05\0\
    \x02\x12\x02\x12\x04\x84\x01\x15\x18\n\r\n\x05\x05\0\x02\x12\x03\x12\x04\
    \x84\x01\x193\n\x10\n\x08\x05\0\x02\x12\x03\xbe\xf3\x04\x12\x04\x84\x01\
    \x1a2\n0\n\x04\x05\0\x02\x13\x12\x06\x87\x01\x02\x88\x014\x1a\x20\x20To\
    \x20create\x20model\x20version\x20export\n\n\r\n\x05\x05\0\x02\x13\x01\
    \x12\x04\x87\x01\x02\x12\n\r\n\x05\x05\0\x02\x13\x02\x12\x04\x87\x01\x15\
    \x18\n\x0f\n\x05\x05\0\x02\x13\x03\x12\x06\x87\x01\x19\x88\x013\n\x10\n\
    \x08\x05\0\x02\x13\x03\xbe\xf3\x04\x12\x04\x87\x01\x1a2\n\x11\n\t\x05\0\
    \x02\x13\x03\xbf\xf3\x04\0\x12\x04\x88\x01\x042\nW\n\x04\x05\0\x02\x14\
    \x12\x06\x8d\x01\x02\x8e\x01C\x1a\"\x20Write\x20to\x20the\x20workflows\
    \x20DB\x20table.\n2#\x20TODO:\x20No\x20model\x20get\x20metrics\x20scope.\
    \n\n\r\n\x05\x05\0\x02\x14\x01\x12\x04\x8d\x01\x02\x0f\n\r\n\x05\x05\0\
    \x02\x14\x02\x12\x04\x8d\x01\x12\x14\n\x0f\n\x05\x05\0\x02\x14\x03\x12\
    \x06\x8d\x01\x15\x8e\x01B\n\x10\n\x08\x05\0\x02\x14\x03\xbe\xf3\x04\x12\
    \x04\x8d\x01\x16.\n\x11\n\t\x05\0\x02\x14\x03\xbf\xf3\x04\0\x12\x04\x8e\
    \x01\x16A\n1\n\x04\x05\0\x02\x15\x12\x04\x91\x01\x020\x1a#\x20Read\x20fr\
    om\x20the\x20workflows\x20DB\x20table.\n\n\r\n\x05\x05\0\x02\x15\x01\x12\
    \x04\x91\x01\x02\x0f\n\r\n\x05\x05\0\x02\x15\x02\x12\x04\x91\x01\x12\x14\
    \n\r\n\x05\x05\0\x02\x15\x03\x12\x04\x91\x01\x15/\n\x10\n\x08\x05\0\x02\
    \x15\x03\xbe\xf3\x04\x12\x04\x91\x01\x16.\n;\n\x04\x05\0\x02\x16\x12\x06\
    \x95\x01\x02\x98\x01+\x1a+\x20To\x20patch\x20we\x20need\x20read/write.\n\
    \x20Deprecated.\n\n\r\n\x05\x05\0\x02\x16\x01\x12\x04\x95\x01\x02\x11\n\
    \r\n\x05\x05\0\x02\x16\x02\x12\x04\x95\x01\x14\x16\n\x0f\n\x05\x05\0\x02\
    \x16\x03\x12\x06\x95\x01\x17\x98\x01*\n\x10\n\x08\x05\0\x02\x16\x03\xbe\
    \xf3\x04\x12\x04\x95\x01\x180\n\x11\n\t\x05\0\x02\x16\x03\xbf\xf3\x04\0\
    \x12\x04\x96\x01\x18C\n\x11\n\t\x05\0\x02\x16\x03\xbf\xf3\x04\x01\x12\
    \x04\x97\x01\x18C\n\x0e\n\x06\x05\0\x02\x16\x03\x01\x12\x04\x98\x01\x18)\
    \n/\n\x04\x05\0\x02\x17\x12\x06\x9b\x01\x02\x9d\x01F\x1a\x1f\x20To\x20de\
    lete\x20we\x20need\x20read/write.\n\n\r\n\x05\x05\0\x02\x17\x01\x12\x04\
    \x9b\x01\x02\x12\n\r\n\x05\x05\0\x02\x17\x02\x12\x04\x9b\x01\x15\x17\n\
    \x0f\n\x05\x05\0\x02\x17\x03\x12\x06\x9b\x01\x18\x9d\x01E\n\x10\n\x08\
    \x05\0\x02\x17\x03\xbe\xf3\x04\x12\x04\x9b\x01\x191\n\x11\n\t\x05\0\x02\
    \x17\x03\xbf\xf3\x04\0\x12\x04\x9c\x01\x19D\n\x11\n\t\x05\0\x02\x17\x03\
    \xbf\xf3\x04\x01\x12\x04\x9d\x01\x19D\n\x0c\n\x04\x05\0\x02\x18\x12\x04\
    \x9f\x01\x026\n\r\n\x05\x05\0\x02\x18\x01\x12\x04\x9f\x01\x02\x15\n\r\n\
    \x05\x05\0\x02\x18\x02\x12\x04\x9f\x01\x18\x1a\n\r\n\x05\x05\0\x02\x18\
    \x03\x12\x04\x9f\x01\x1b5\n\x10\n\x08\x05\0\x02\x18\x03\xbe\xf3\x04\x12\
    \x04\x9f\x01\x1c4\n\x0e\n\x04\x05\0\x02\x19\x12\x06\xa1\x01\x02\xa2\x01N\
    \n\r\n\x05\x05\0\x02\x19\x01\x12\x04\xa1\x01\x02\x15\n\r\n\x05\x05\0\x02\
    \x19\x02\x12\x04\xa1\x01\x18\x1a\n\x0f\n\x05\x05\0\x02\x19\x03\x12\x06\
    \xa1\x01\x1b\xa2\x01M\n\x10\n\x08\x05\0\x02\x19\x03\xbe\xf3\x04\x12\x04\
    \xa1\x01\x1c4\n\x11\n\t\x05\0\x02\x19\x03\xbf\xf3\x04\0\x12\x04\xa2\x01\
    \x1bL\n\x0e\n\x04\x05\0\x02\x1a\x12\x06\xa4\x01\x02\xa6\x01Q\n\r\n\x05\
    \x05\0\x02\x1a\x01\x12\x04\xa4\x01\x02\x18\n\r\n\x05\x05\0\x02\x1a\x02\
    \x12\x04\xa4\x01\x1b\x1d\n\x0f\n\x05\x05\0\x02\x1a\x03\x12\x06\xa4\x01\
    \x1e\xa6\x01P\n\x10\n\x08\x05\0\x02\x1a\x03\xbe\xf3\x04\x12\x04\xa4\x01\
    \x1f7\n\x11\n\t\x05\0\x02\x1a\x03\xbf\xf3\x04\0\x12\x04\xa5\x01\x1eO\n\
    \x11\n\t\x05\0\x02\x1a\x03\xbf\xf3\x04\x01\x12\x04\xa6\x01\x1eO\nC\n\x04\
    \x05\0\x02\x1b\x12\x06\xaa\x01\x02\xab\x012\x1a3\x20Write\x20to\x20the\
    \x20visualizations\x20DB\x20table.\n\x20Deprecated\n\n\r\n\x05\x05\0\x02\
    \x1b\x01\x12\x04\xaa\x01\x02\x18\n\r\n\x05\x05\0\x02\x1b\x02\x12\x04\xaa\
    \x01\x1b\x1d\n\x0f\n\x05\x05\0\x02\x1b\x03\x12\x06\xaa\x01\x1e\xab\x011\
    \n\x11\n\t\x05\0\x02\x1b\x03\xbf\xf3\x04\0\x12\x04\xaa\x01\x1fS\n\x0e\n\
    \x06\x05\0\x02\x1b\x03\x01\x12\x04\xab\x01\x1f0\nB\n\x04\x05\0\x02\x1c\
    \x12\x04\xaf\x01\x022\x1a4\x20Read\x20from\x20the\x20visualizations\x20D\
    B\x20table.\n\x20Deprecated\n\n\r\n\x05\x05\0\x02\x1c\x01\x12\x04\xaf\
    \x01\x02\x18\n\r\n\x05\x05\0\x02\x1c\x02\x12\x04\xaf\x01\x1b\x1d\n\r\n\
    \x05\x05\0\x02\x1c\x03\x12\x04\xaf\x01\x1e1\n\x0e\n\x06\x05\0\x02\x1c\
    \x03\x01\x12\x04\xaf\x01\x1f0\n4\n\x04\x05\0\x02\x1d\x12\x06\xb2\x01\x02\
    \xb3\x01G\x1a$\x20Write\x20to\x20the\x20annotations\x20DB\x20table.\n\n\
    \r\n\x05\x05\0\x02\x1d\x01\x12\x04\xb2\x01\x02\x11\n\r\n\x05\x05\0\x02\
    \x1d\x02\x12\x04\xb2\x01\x14\x16\n\x0f\n\x05\x05\0\x02\x1d\x03\x12\x06\
    \xb2\x01\x17\xb3\x01F\n\x10\n\x08\x05\0\x02\x1d\x03\xbe\xf3\x04\x12\x04\
    \xb2\x01\x180\n\x11\n\t\x05\0\x02\x1d\x03\xbf\xf3\x04\0\x12\x04\xb3\x01\
    \x18E\n3\n\x04\x05\0\x02\x1e\x12\x04\xb6\x01\x022\x1a%\x20Read\x20from\
    \x20the\x20annotations\x20DB\x20table.\n\n\r\n\x05\x05\0\x02\x1e\x01\x12\
    \x04\xb6\x01\x02\x11\n\r\n\x05\x05\0\x02\x1e\x02\x12\x04\xb6\x01\x14\x16\
    \n\r\n\x05\x05\0\x02\x1e\x03\x12\x04\xb6\x01\x171\n\x10\n\x08\x05\0\x02\
    \x1e\x03\xbe\xf3\x04\x12\x04\xb6\x01\x180\n;\n\x04\x05\0\x02\x1f\x12\x06\
    \xba\x01\x02\xbd\x01-\x1a+\x20To\x20patch\x20we\x20need\x20read/write.\n\
    \x20Deprecated.\n\n\r\n\x05\x05\0\x02\x1f\x01\x12\x04\xba\x01\x02\x13\n\
    \r\n\x05\x05\0\x02\x1f\x02\x12\x04\xba\x01\x16\x18\n\x0f\n\x05\x05\0\x02\
    \x1f\x03\x12\x06\xba\x01\x19\xbd\x01,\n\x10\n\x08\x05\0\x02\x1f\x03\xbe\
    \xf3\x04\x12\x04\xba\x01\x1a2\n\x11\n\t\x05\0\x02\x1f\x03\xbf\xf3\x04\0\
    \x12\x04\xbb\x01\x1aG\n\x11\n\t\x05\0\x02\x1f\x03\xbf\xf3\x04\x01\x12\
    \x04\xbc\x01\x1aG\n\x0e\n\x06\x05\0\x02\x1f\x03\x01\x12\x04\xbd\x01\x1a+\
    \n/\n\x04\x05\0\x02\x20\x12\x06\xc0\x01\x02\xc2\x01J\x1a\x1f\x20To\x20de\
    lete\x20we\x20need\x20read/write.\n\n\r\n\x05\x05\0\x02\x20\x01\x12\x04\
    \xc0\x01\x02\x14\n\r\n\x05\x05\0\x02\x20\x02\x12\x04\xc0\x01\x17\x19\n\
    \x0f\n\x05\x05\0\x02\x20\x03\x12\x06\xc0\x01\x1a\xc2\x01I\n\x10\n\x08\
    \x05\0\x02\x20\x03\xbe\xf3\x04\x12\x04\xc0\x01\x1b3\n\x11\n\t\x05\0\x02\
    \x20\x03\xbf\xf3\x04\0\x12\x04\xc1\x01\x1bH\n\x11\n\t\x05\0\x02\x20\x03\
    \xbf\xf3\x04\x01\x12\x04\xc2\x01\x1bH\n3\n\x04\x05\0\x02!\x12\x06\xc7\
    \x01\x02\xc8\x01E\x1a#\x20Write\x20to\x20the\x20collectors\x20DB\x20tabl\
    e.\n\n\r\n\x05\x05\0\x02!\x01\x12\x04\xc7\x01\x02\x10\n\r\n\x05\x05\0\
    \x02!\x02\x12\x04\xc7\x01\x13\x15\n\x0f\n\x05\x05\0\x02!\x03\x12\x06\xc7\
    \x01\x16\xc8\x01D\n\x10\n\x08\x05\0\x02!\x03\xbe\xf3\x04\x12\x04\xc7\x01\
    \x17/\n\x11\n\t\x05\0\x02!\x03\xbf\xf3\x04\0\x12\x04\xc8\x01\x17C\n2\n\
    \x04\x05\0\x02\"\x12\x04\xcb\x01\x021\x1a$\x20Read\x20from\x20the\x20col\
    lectors\x20DB\x20table.\n\n\r\n\x05\x05\0\x02\"\x01\x12\x04\xcb\x01\x02\
    \x10\n\r\n\x05\x05\0\x02\"\x02\x12\x04\xcb\x01\x13\x15\n\r\n\x05\x05\0\
    \x02\"\x03\x12\x04\xcb\x01\x160\n\x10\n\x08\x05\0\x02\"\x03\xbe\xf3\x04\
    \x12\x04\xcb\x01\x17/\n/\n\x04\x05\0\x02#\x12\x06\xce\x01\x02\xd0\x01H\
    \x1a\x1f\x20To\x20delete\x20we\x20need\x20read/write.\n\n\r\n\x05\x05\0\
    \x02#\x01\x12\x04\xce\x01\x02\x13\n\r\n\x05\x05\0\x02#\x02\x12\x04\xce\
    \x01\x16\x18\n\x0f\n\x05\x05\0\x02#\x03\x12\x06\xce\x01\x19\xd0\x01G\n\
    \x10\n\x08\x05\0\x02#\x03\xbe\xf3\x04\x12\x04\xce\x01\x1a2\n\x11\n\t\x05\
    \0\x02#\x03\xbf\xf3\x04\0\x12\x04\xcf\x01\x1aF\n\x11\n\t\x05\0\x02#\x03\
    \xbf\xf3\x04\x01\x12\x04\xd0\x01\x1aF\n-\n\x04\x05\0\x02$\x12\x06\xd4\
    \x01\x02\xd5\x019\x1a\x1d\x20Write\x20to\x20the\x20apps\x20DB\x20table.\
    \n\n\r\n\x05\x05\0\x02$\x01\x12\x04\xd4\x01\x02\n\n\r\n\x05\x05\0\x02$\
    \x02\x12\x04\xd4\x01\r\x0f\n\x0f\n\x05\x05\0\x02$\x03\x12\x06\xd4\x01\
    \x10\xd5\x018\n\x10\n\x08\x05\0\x02$\x03\xbe\xf3\x04\x12\x04\xd4\x01\x11\
    )\n\x11\n\t\x05\0\x02$\x03\xbf\xf3\x04\0\x12\x04\xd5\x01\x117\n,\n\x04\
    \x05\0\x02%\x12\x04\xd8\x01\x02+\x1a\x1e\x20Read\x20from\x20the\x20apps\
    \x20DB\x20table.\n\n\r\n\x05\x05\0\x02%\x01\x12\x04\xd8\x01\x02\n\n\r\n\
    \x05\x05\0\x02%\x02\x12\x04\xd8\x01\r\x0f\n\r\n\x05\x05\0\x02%\x03\x12\
    \x04\xd8\x01\x10*\n\x10\n\x08\x05\0\x02%\x03\xbe\xf3\x04\x12\x04\xd8\x01\
    \x11)\n/\n\x04\x05\0\x02&\x12\x06\xdb\x01\x02\xdd\x01<\x1a\x1f\x20To\x20\
    delete\x20we\x20need\x20read/write.\n\n\r\n\x05\x05\0\x02&\x01\x12\x04\
    \xdb\x01\x02\r\n\r\n\x05\x05\0\x02&\x02\x12\x04\xdb\x01\x10\x12\n\x0f\n\
    \x05\x05\0\x02&\x03\x12\x06\xdb\x01\x13\xdd\x01;\n\x10\n\x08\x05\0\x02&\
    \x03\xbe\xf3\x04\x12\x04\xdb\x01\x14,\n\x11\n\t\x05\0\x02&\x03\xbf\xf3\
    \x04\0\x12\x04\xdc\x01\x14:\n\x11\n\t\x05\0\x02&\x03\xbf\xf3\x04\x01\x12\
    \x04\xdd\x01\x14:\n-\n\x04\x05\0\x02'\x12\x06\xe0\x01\x02\xe1\x019\x1a\
    \x1d\x20Write\x20to\x20the\x20keys\x20DB\x20table.\n\n\r\n\x05\x05\0\x02\
    '\x01\x12\x04\xe0\x01\x02\n\n\r\n\x05\x05\0\x02'\x02\x12\x04\xe0\x01\r\
    \x0f\n\x0f\n\x05\x05\0\x02'\x03\x12\x06\xe0\x01\x10\xe1\x018\n\x10\n\x08\
    \x05\0\x02'\x03\xbe\xf3\x04\x12\x04\xe0\x01\x11)\n\x11\n\t\x05\0\x02'\
    \x03\xbf\xf3\x04\0\x12\x04\xe1\x01\x117\n,\n\x04\x05\0\x02(\x12\x04\xe4\
    \x01\x02+\x1a\x1e\x20Read\x20from\x20the\x20keys\x20DB\x20table.\n\n\r\n\
    \x05\x05\0\x02(\x01\x12\x04\xe4\x01\x02\n\n\r\n\x05\x05\0\x02(\x02\x12\
    \x04\xe4\x01\r\x0f\n\r\n\x05\x05\0\x02(\x03\x12\x04\xe4\x01\x10*\n\x10\n\
    \x08\x05\0\x02(\x03\xbe\xf3\x04\x12\x04\xe4\x01\x11)\n/\n\x04\x05\0\x02)\
    \x12\x06\xe7\x01\x02\xe9\x01<\x1a\x1f\x20To\x20delete\x20we\x20need\x20r\
    ead/write.\n\n\r\n\x05\x05\0\x02)\x01\x12\x04\xe7\x01\x02\r\n\r\n\x05\
    \x05\0\x02)\x02\x12\x04\xe7\x01\x10\x12\n\x0f\n\x05\x05\0\x02)\x03\x12\
    \x06\xe7\x01\x13\xe9\x01;\n\x10\n\x08\x05\0\x02)\x03\xbe\xf3\x04\x12\x04\
    \xe7\x01\x14,\n\x11\n\t\x05\0\x02)\x03\xbf\xf3\x04\0\x12\x04\xe8\x01\x14\
    :\n\x11\n\t\x05\0\x02)\x03\xbf\xf3\x04\x01\x12\x04\xe9\x01\x14:\n3\n\x04\
    \x05\0\x02*\x12\x06\xec\x01\x02\xed\x01K\x1a#\x20Write\x20to\x20the\x20a\
    pp\x20sharing\x20DB\x20table\n\n\r\n\x05\x05\0\x02*\x01\x12\x04\xec\x01\
    \x02\x13\n\r\n\x05\x05\0\x02*\x02\x12\x04\xec\x01\x16\x18\n\x0f\n\x05\
    \x05\0\x02*\x03\x12\x06\xec\x01\x19\xed\x01J\n\x10\n\x08\x05\0\x02*\x03\
    \xbe\xf3\x04\x12\x04\xec\x01\x1a2\n\x11\n\t\x05\0\x02*\x03\xbf\xf3\x04\0\
    \x12\x04\xed\x01\x1aI\n2\n\x04\x05\0\x02+\x12\x04\xf0\x01\x024\x1a$\x20R\
    ead\x20from\x20the\x20app\x20sharing\x20DB\x20table\n\n\r\n\x05\x05\0\
    \x02+\x01\x12\x04\xf0\x01\x02\x13\n\r\n\x05\x05\0\x02+\x02\x12\x04\xf0\
    \x01\x16\x18\n\r\n\x05\x05\0\x02+\x03\x12\x04\xf0\x01\x193\n\x10\n\x08\
    \x05\0\x02+\x03\xbe\xf3\x04\x12\x04\xf0\x01\x1a2\n.\n\x04\x05\0\x02,\x12\
    \x06\xf3\x01\x02\xf5\x01N\x1a\x1e\x20To\x20delete\x20we\x20need\x20read/\
    write\n\n\r\n\x05\x05\0\x02,\x01\x12\x04\xf3\x01\x02\x16\n\r\n\x05\x05\0\
    \x02,\x02\x12\x04\xf3\x01\x19\x1b\n\x0f\n\x05\x05\0\x02,\x03\x12\x06\xf3\
    \x01\x1c\xf5\x01M\n\x10\n\x08\x05\0\x02,\x03\xbe\xf3\x04\x12\x04\xf3\x01\
    \x1d5\n\x11\n\t\x05\0\x02,\x03\xbf\xf3\x04\0\x12\x04\xf4\x01\x1dL\n\x11\
    \n\t\x05\0\x02,\x03\xbf\xf3\x04\x01\x12\x04\xf5\x01\x1dL\n,\n\x04\x05\0\
    \x02-\x12\x06\xf8\x01\x02\xf9\x01E\x1a\x1c\x20Write\x20to\x20the\x20metr\
    ics\x20table\n\n\r\n\x05\x05\0\x02-\x01\x12\x04\xf8\x01\x02\r\n\r\n\x05\
    \x05\0\x02-\x02\x12\x04\xf8\x01\x10\x12\n\x0f\n\x05\x05\0\x02-\x03\x12\
    \x06\xf8\x01\x13\xf9\x01D\n\x10\n\x08\x05\0\x02-\x03\xbe\xf3\x04\x12\x04\
    \xf8\x01\x14,\n\x11\n\t\x05\0\x02-\x03\xbf\xf3\x04\0\x12\x04\xf9\x01\x1a\
    C\n'\n\x04\x05\0\x02.\x12\x04\xfc\x01\x02.\x1a\x19\x20Read\x20from\x20me\
    trics\x20table\n\n\r\n\x05\x05\0\x02.\x01\x12\x04\xfc\x01\x02\r\n\r\n\
    \x05\x05\0\x02.\x02\x12\x04\xfc\x01\x10\x12\n\r\n\x05\x05\0\x02.\x03\x12\
    \x04\xfc\x01\x13-\n\x10\n\x08\x05\0\x02.\x03\xbe\xf3\x04\x12\x04\xfc\x01\
    \x14,\n.\n\x04\x05\0\x02/\x12\x06\xff\x01\x02\x81\x02H\x1a\x1e\x20To\x20\
    delete\x20we\x20need\x20read/write\n\n\r\n\x05\x05\0\x02/\x01\x12\x04\
    \xff\x01\x02\x10\n\r\n\x05\x05\0\x02/\x02\x12\x04\xff\x01\x13\x15\n\x0f\
    \n\x05\x05\0\x02/\x03\x12\x06\xff\x01\x16\x81\x02G\n\x10\n\x08\x05\0\x02\
    /\x03\xbe\xf3\x04\x12\x04\xff\x01\x17/\n\x11\n\t\x05\0\x02/\x03\xbf\xf3\
    \x04\0\x12\x04\x80\x02\x1dF\n\x11\n\t\x05\0\x02/\x03\xbf\xf3\x04\x01\x12\
    \x04\x81\x02\x1dF\n*\n\x04\x05\0\x020\x12\x06\x84\x02\x02\x85\x02:\x1a\
    \x1a\x20Write\x20to\x20tasks\x20DB\x20table.\n\n\r\n\x05\x05\0\x020\x01\
    \x12\x04\x84\x02\x02\x0b\n\r\n\x05\x05\0\x020\x02\x12\x04\x84\x02\x0e\
    \x10\n\x0f\n\x05\x05\0\x020\x03\x12\x06\x84\x02\x11\x85\x029\n\x10\n\x08\
    \x05\0\x020\x03\xbe\xf3\x04\x12\x04\x84\x02\x12*\n\x11\n\t\x05\0\x020\
    \x03\xbf\xf3\x04\0\x12\x04\x85\x02\x118\n-\n\x04\x05\0\x021\x12\x04\x88\
    \x02\x02,\x1a\x1f\x20Read\x20from\x20the\x20tasks\x20DB\x20table.\n\n\r\
    \n\x05\x05\0\x021\x01\x12\x04\x88\x02\x02\x0b\n\r\n\x05\x05\0\x021\x02\
    \x12\x04\x88\x02\x0e\x10\n\r\n\x05\x05\0\x021\x03\x12\x04\x88\x02\x11+\n\
    \x10\n\x08\x05\0\x021\x03\xbe\xf3\x04\x12\x04\x88\x02\x12*\n.\n\x04\x05\
    \0\x022\x12\x06\x8b\x02\x02\x8d\x02=\x1a\x1e\x20To\x20delete\x20we\x20ne\
    ed\x20read/write\n\n\r\n\x05\x05\0\x022\x01\x12\x04\x8b\x02\x02\x0e\n\r\
    \n\x05\x05\0\x022\x02\x12\x04\x8b\x02\x11\x13\n\x0f\n\x05\x05\0\x022\x03\
    \x12\x06\x8b\x02\x14\x8d\x02<\n\x10\n\x08\x05\0\x022\x03\xbe\xf3\x04\x12\
    \x04\x8b\x02\x15-\n\x11\n\t\x05\0\x022\x03\xbf\xf3\x04\0\x12\x04\x8c\x02\
    \x14;\n\x11\n\t\x05\0\x022\x03\xbf\xf3\x04\x01\x12\x04\x8d\x02\x14;\n9\n\
    \x04\x05\0\x023\x12\x06\x90\x02\x02\x91\x028\x1a)\x20Write\x20to\x20the\
    \x20password_policies\x20DB\x20table\n\n\r\n\x05\x05\0\x023\x01\x12\x04\
    \x90\x02\x02\x16\n\r\n\x05\x05\0\x023\x02\x12\x04\x90\x02\x19\x1b\n\x0f\
    \n\x05\x05\0\x023\x03\x12\x06\x90\x02\x1c\x91\x027\n\x10\n\x08\x05\0\x02\
    3\x03\xbe\xf3\x04\x12\x04\x90\x02\x1d5\n\x11\n\t\x05\0\x023\x03\xbf\xf3\
    \x04\0\x12\x04\x91\x02\x046\n8\n\x04\x05\0\x024\x12\x04\x94\x02\x027\x1a\
    *\x20Read\x20from\x20the\x20password_policies\x20DB\x20table\n\n\r\n\x05\
    \x05\0\x024\x01\x12\x04\x94\x02\x02\x16\n\r\n\x05\x05\0\x024\x02\x12\x04\
    \x94\x02\x19\x1b\n\r\n\x05\x05\0\x024\x03\x12\x04\x94\x02\x1c6\n\x10\n\
    \x08\x05\0\x024\x03\xbe\xf3\x04\x12\x04\x94\x02\x1d5\n@\n\x04\x05\0\x025\
    \x12\x06\x97\x02\x02\x99\x02;\x1a0\x20To\x20delete\x20password_policies\
    \x20we\x20need\x20read/write\n\n\r\n\x05\x05\0\x025\x01\x12\x04\x97\x02\
    \x02\x19\n\r\n\x05\x05\0\x025\x02\x12\x04\x97\x02\x1c\x1e\n\x0f\n\x05\
    \x05\0\x025\x03\x12\x06\x97\x02\x1f\x99\x02:\n\x10\n\x08\x05\0\x025\x03\
    \xbe\xf3\x04\x12\x04\x97\x02\x208\n\x11\n\t\x05\0\x025\x03\xbf\xf3\x04\0\
    \x12\x04\x98\x02\x079\n\x11\n\t\x05\0\x025\x03\xbf\xf3\x04\x01\x12\x04\
    \x99\x02\x079\n,\n\x04\x05\0\x026\x12\x04\xa2\x02\x022\x1a\x1e\x20Read\
    \x20from\x20label\x20orders\x20table\n\n\r\n\x05\x05\0\x026\x01\x12\x04\
    \xa2\x02\x02\x11\n\r\n\x05\x05\0\x026\x02\x12\x04\xa2\x02\x14\x16\n\r\n\
    \x05\x05\0\x026\x03\x12\x04\xa2\x02\x171\n\x10\n\x08\x05\0\x026\x03\xbe\
    \xf3\x04\x12\x04\xa2\x02\x180\n-\n\x04\x05\0\x027\x12\x06\xa5\x02\x02\
    \xa6\x02H\x1a\x1d\x20Write\x20to\x20label\x20orders\x20table\n\n\r\n\x05\
    \x05\0\x027\x01\x12\x04\xa5\x02\x02\x11\n\r\n\x05\x05\0\x027\x02\x12\x04\
    \xa5\x02\x14\x16\n\x0f\n\x05\x05\0\x027\x03\x12\x06\xa5\x02\x17\xa6\x02G\
    \n\x10\n\x08\x05\0\x027\x03\xbe\xf3\x04\x12\x04\xa5\x02\x180\n\x11\n\t\
    \x05\0\x027\x03\xbf\xf3\x04\0\x12\x04\xa6\x02\x19F\n;\n\x04\x05\0\x028\
    \x12\x06\xa9\x02\x02\xab\x02K\x1a+\x20To\x20delete\x20label\x20orders\
    \x20we\x20need\x20read/write\n\n\r\n\x05\x05\0\x028\x01\x12\x04\xa9\x02\
    \x02\x14\n\r\n\x05\x05\0\x028\x02\x12\x04\xa9\x02\x17\x19\n\x0f\n\x05\
    \x05\0\x028\x03\x12\x06\xa9\x02\x1a\xab\x02J\n\x10\n\x08\x05\0\x028\x03\
    \xbe\xf3\x04\x12\x04\xa9\x02\x1b3\n\x11\n\t\x05\0\x028\x03\xbf\xf3\x04\0\
    \x12\x04\xaa\x02\x1cI\n\x11\n\t\x05\0\x028\x03\xbf\xf3\x04\x01\x12\x04\
    \xab\x02\x1cI\n4\n\x04\x05\0\x029\x12\x04\xae\x02\x029\x1a&\x20Read\x20f\
    rom\x20user_feature_configs\x20table\n\n\r\n\x05\x05\0\x029\x01\x12\x04\
    \xae\x02\x02\x18\n\r\n\x05\x05\0\x029\x02\x12\x04\xae\x02\x1b\x1d\n\r\n\
    \x05\x05\0\x029\x03\x12\x04\xae\x02\x1e8\n\x10\n\x08\x05\0\x029\x03\xbe\
    \xf3\x04\x12\x04\xae\x02\x1f7\n<\n\x04\x05\0\x02:\x12\x06\xc7\x02\x02\
    \xc8\x02B\x1a,\x20CRUD\x20on\x20FindDuplicateAnnotationsJobs\x20table\n\
    \n\r\n\x05\x05\0\x02:\x01\x12\x04\xc7\x02\x02\"\n\r\n\x05\x05\0\x02:\x02\
    \x12\x04\xc7\x02%(\n\x0f\n\x05\x05\0\x02:\x03\x12\x06\xc7\x02)\xc8\x02A\
    \n\x10\n\x08\x05\0\x02:\x03\xbe\xf3\x04\x12\x04\xc7\x02*B\n\x11\n\t\x05\
    \0\x02:\x03\xbf\xf3\x04\0\x12\x04\xc8\x02\x02@\n\x0c\n\x04\x05\0\x02;\
    \x12\x04\xc9\x02\x02D\n\r\n\x05\x05\0\x02;\x01\x12\x04\xc9\x02\x02\"\n\r\
    \n\x05\x05\0\x02;\x02\x12\x04\xc9\x02%(\n\r\n\x05\x05\0\x02;\x03\x12\x04\
    \xc9\x02)C\n\x10\n\x08\x05\0\x02;\x03\xbe\xf3\x04\x12\x04\xc9\x02*B\n\
    \x0e\n\x04\x05\0\x02<\x12\x06\xca\x02\x02\xcc\x02H\n\r\n\x05\x05\0\x02<\
    \x01\x12\x04\xca\x02\x02%\n\r\n\x05\x05\0\x02<\x02\x12\x04\xca\x02(+\n\
    \x0f\n\x05\x05\0\x02<\x03\x12\x06\xca\x02,\xcc\x02G\n\x10\n\x08\x05\0\
    \x02<\x03\xbe\xf3\x04\x12\x04\xca\x02-E\n\x11\n\t\x05\0\x02<\x03\xbf\xf3\
    \x04\0\x12\x04\xcb\x02\x08F\n\x11\n\t\x05\0\x02<\x03\xbf\xf3\x04\x01\x12\
    \x04\xcc\x02\x08F\n\x0c\n\x04\x05\0\x02=\x12\x04\xcf\x02\x020\n\r\n\x05\
    \x05\0\x02=\x01\x12\x04\xcf\x02\x02\x0e\n\r\n\x05\x05\0\x02=\x02\x12\x04\
    \xcf\x02\x11\x14\n\r\n\x05\x05\0\x02=\x03\x12\x04\xcf\x02\x15/\n\x10\n\
    \x08\x05\0\x02=\x03\xbe\xf3\x04\x12\x04\xcf\x02\x16.\n\x0e\n\x04\x05\0\
    \x02>\x12\x06\xd0\x02\x02\xd1\x02@\n\r\n\x05\x05\0\x02>\x01\x12\x04\xd0\
    \x02\x02\x0e\n\r\n\x05\x05\0\x02>\x02\x12\x04\xd0\x02\x11\x14\n\x0f\n\
    \x05\x05\0\x02>\x03\x12\x06\xd0\x02\x15\xd1\x02?\n\x10\n\x08\x05\0\x02>\
    \x03\xbe\xf3\x04\x12\x04\xd0\x02\x16.\n\x11\n\t\x05\0\x02>\x03\xbf\xf3\
    \x04\0\x12\x04\xd1\x02\x14>\n\x0e\n\x04\x05\0\x02?\x12\x06\xd2\x02\x02\
    \xd4\x02C\n\r\n\x05\x05\0\x02?\x01\x12\x04\xd2\x02\x02\x11\n\r\n\x05\x05\
    \0\x02?\x02\x12\x04\xd2\x02\x14\x17\n\x0f\n\x05\x05\0\x02?\x03\x12\x06\
    \xd2\x02\x18\xd4\x02B\n\x10\n\x08\x05\0\x02?\x03\xbe\xf3\x04\x12\x04\xd2\
    \x02\x191\n\x11\n\t\x05\0\x02?\x03\xbf\xf3\x04\0\x12\x04\xd3\x02\x17A\n\
    \x11\n\t\x05\0\x02?\x03\xbf\xf3\x04\x01\x12\x04\xd4\x02\x17A\n1\n\x04\
    \x05\0\x02@\x12\x06\xd7\x02\x02\xd8\x02>\x1a!\x20Write\x20to\x20the\x20m\
    odules\x20DB\x20tables.\n\n\r\n\x05\x05\0\x02@\x01\x12\x04\xd7\x02\x02\r\
    \n\r\n\x05\x05\0\x02@\x02\x12\x04\xd7\x02\x10\x13\n\x0f\n\x05\x05\0\x02@\
    \x03\x12\x06\xd7\x02\x14\xd8\x02=\n\x10\n\x08\x05\0\x02@\x03\xbe\xf3\x04\
    \x12\x04\xd7\x02\x15-\n\x11\n\t\x05\0\x02@\x03\xbf\xf3\x04\0\x12\x04\xd8\
    \x02\x13<\nE\n\x04\x05\0\x02A\x12\x04\xdb\x02\x02/\x1a7\x20Read\x20from\
    \x20the\x20modules\x20and\x20modules\x20versions\x20DB\x20tables.\n\n\r\
    \n\x05\x05\0\x02A\x01\x12\x04\xdb\x02\x02\r\n\r\n\x05\x05\0\x02A\x02\x12\
    \x04\xdb\x02\x10\x13\n\r\n\x05\x05\0\x02A\x03\x12\x04\xdb\x02\x14.\n\x10\
    \n\x08\x05\0\x02A\x03\xbe\xf3\x04\x12\x04\xdb\x02\x15-\n/\n\x04\x05\0\
    \x02B\x12\x06\xde\x02\x02\xe0\x02A\x1a\x1f\x20To\x20delete\x20we\x20need\
    \x20read/write.\n\n\r\n\x05\x05\0\x02B\x01\x12\x04\xde\x02\x02\x10\n\r\n\
    \x05\x05\0\x02B\x02\x12\x04\xde\x02\x13\x16\n\x0f\n\x05\x05\0\x02B\x03\
    \x12\x06\xde\x02\x17\xe0\x02@\n\x10\n\x08\x05\0\x02B\x03\xbe\xf3\x04\x12\
    \x04\xde\x02\x180\n\x11\n\t\x05\0\x02B\x03\xbf\xf3\x04\0\x12\x04\xdf\x02\
    \x16?\n\x11\n\t\x05\0\x02B\x03\xbf\xf3\x04\x01\x12\x04\xe0\x02\x16?\nA\n\
    \x04\x05\0\x02C\x12\x06\xe4\x02\x02\xe6\x02P\x1a1\x20Write\x20to\x20the\
    \x20InstalledModuleVersions\x20DB\x20tables.\n\n\r\n\x05\x05\0\x02C\x01\
    \x12\x04\xe4\x02\x02\x1d\n\r\n\x05\x05\0\x02C\x02\x12\x04\xe4\x02\x20#\n\
    \x0f\n\x05\x05\0\x02C\x03\x12\x06\xe4\x02$\xe6\x02O\n\x10\n\x08\x05\0\
    \x02C\x03\xbe\xf3\x04\x12\x04\xe4\x02%=\n\x11\n\t\x05\0\x02C\x03\xbf\xf3\
    \x04\0\x12\x04\xe5\x02%^\n\x11\n\t\x05\0\x02C\x03\xbf\xf3\x04\x01\x12\
    \x04\xe6\x02%N\ng\n\x04\x05\0\x02D\x12\x06\xe9\x02\x02\xea\x02P\x1aW\x20\
    Read\x20from\x20the\x20InstalledModuleVersions\x20and\x20InstalledModule\
    Versions\x20versions\x20DB\x20tables.\n\n\r\n\x05\x05\0\x02D\x01\x12\x04\
    \xe9\x02\x02\x1d\n\r\n\x05\x05\0\x02D\x02\x12\x04\xe9\x02\x20#\n\x0f\n\
    \x05\x05\0\x02D\x03\x12\x06\xe9\x02$\xea\x02O\n\x10\n\x08\x05\0\x02D\x03\
    \xbe\xf3\x04\x12\x04\xe9\x02%=\n\x11\n\t\x05\0\x02D\x03\xbf\xf3\x04\0\
    \x12\x04\xea\x02%N\n/\n\x04\x05\0\x02E\x12\x06\xed\x02\x02\xf0\x02S\x1a\
    \x1f\x20To\x20delete\x20we\x20need\x20read/write.\n\n\r\n\x05\x05\0\x02E\
    \x01\x12\x04\xed\x02\x02\x20\n\r\n\x05\x05\0\x02E\x02\x12\x04\xed\x02#&\
    \n\x0f\n\x05\x05\0\x02E\x03\x12\x06\xed\x02'\xf0\x02R\n\x10\n\x08\x05\0\
    \x02E\x03\xbe\xf3\x04\x12\x04\xed\x02(@\n\x11\n\t\x05\0\x02E\x03\xbf\xf3\
    \x04\0\x12\x04\xee\x02(a\n\x11\n\t\x05\0\x02E\x03\xbf\xf3\x04\x01\x12\
    \x04\xef\x02(a\n\x11\n\t\x05\0\x02E\x03\xbf\xf3\x04\x02\x12\x04\xf0\x02(\
    Q\n3\n\x04\x05\0\x02F\x12\x04\xf3\x02\x02(\x1a%\x20Make\x20an\x20rpc\x20\
    to\x20our\x20search\x20services.\n\n\r\n\x05\x05\0\x02F\x01\x12\x04\xf3\
    \x02\x02\x08\n\r\n\x05\x05\0\x02F\x02\x12\x04\xf3\x02\x0b\x0c\n\r\n\x05\
    \x05\0\x02F\x03\x12\x04\xf3\x02\r'\n\x10\n\x08\x05\0\x02F\x03\xbe\xf3\
    \x04\x12\x04\xf3\x02\x0e&\n&\n\x04\x05\0\x02G\x12\x04\xf6\x02\x023\x1a\
    \x18\x20To\x20get\x20a\x20saved\x20search.\n\n\r\n\x05\x05\0\x02G\x01\
    \x12\x04\xf6\x02\x02\x11\n\r\n\x05\x05\0\x02G\x02\x12\x04\xf6\x02\x14\
    \x17\n\r\n\x05\x05\0\x02G\x03\x12\x04\xf6\x02\x182\n\x10\n\x08\x05\0\x02\
    G\x03\xbe\xf3\x04\x12\x04\xf6\x02\x191\n'\n\x04\x05\0\x02H\x12\x06\xf9\
    \x02\x02\xfa\x023\x1a\x17\x20To\x20add\x20a\x20saved\x20search\n\n\r\n\
    \x05\x05\0\x02H\x01\x12\x04\xf9\x02\x02\x11\n\r\n\x05\x05\0\x02H\x02\x12\
    \x04\xf9\x02\x14\x17\n\x0f\n\x05\x05\0\x02H\x03\x12\x06\xf9\x02\x18\xfa\
    \x022\n\x10\n\x08\x05\0\x02H\x03\xbe\xf3\x04\x12\x04\xf9\x02\x191\n\x11\
    \n\t\x05\0\x02H\x03\xbf\xf3\x04\0\x12\x04\xfa\x02\x041\n*\n\x04\x05\0\
    \x02I\x12\x06\xfd\x02\x02\xff\x023\x1a\x1a\x20To\x20delete\x20a\x20saved\
    \x20search\n\n\r\n\x05\x05\0\x02I\x01\x12\x04\xfd\x02\x02\x14\n\r\n\x05\
    \x05\0\x02I\x02\x12\x04\xfd\x02\x15\x18\n\x0f\n\x05\x05\0\x02I\x03\x12\
    \x06\xfd\x02\x19\xff\x022\n\x10\n\x08\x05\0\x02I\x03\xbe\xf3\x04\x12\x04\
    \xfd\x02\x1a2\n\x11\n\t\x05\0\x02I\x03\xbf\xf3\x04\0\x12\x04\xfe\x02\x04\
    1\n\x11\n\t\x05\0\x02I\x03\xbf\xf3\x04\x01\x12\x04\xff\x02\x041\n\x0c\n\
    \x04\x05\0\x02J\x12\x04\x81\x03\x02>\n\r\n\x05\x05\0\x02J\x01\x12\x04\
    \x81\x03\x02\x1e\n\r\n\x05\x05\0\x02J\x02\x12\x04\x81\x03\x1f\"\n\r\n\
    \x05\x05\0\x02J\x03\x12\x04\x81\x03#=\n\x10\n\x08\x05\0\x02J\x03\xbe\xf3\
    \x04\x12\x04\x81\x03$<\n\x0c\n\x04\x05\0\x02K\x12\x04\x82\x03\x02A\n\r\n\
    \x05\x05\0\x02K\x01\x12\x04\x82\x03\x02!\n\r\n\x05\x05\0\x02K\x02\x12\
    \x04\x82\x03\"%\n\r\n\x05\x05\0\x02K\x03\x12\x04\x82\x03&@\n\x10\n\x08\
    \x05\0\x02K\x03\xbe\xf3\x04\x12\x04\x82\x03'?\n\x0c\n\x04\x05\0\x02L\x12\
    \x04\x84\x03\x02:\n\r\n\x05\x05\0\x02L\x01\x12\x04\x84\x03\x02\x1a\n\r\n\
    \x05\x05\0\x02L\x02\x12\x04\x84\x03\x1b\x1e\n\r\n\x05\x05\0\x02L\x03\x12\
    \x04\x84\x03\x1f9\n\x10\n\x08\x05\0\x02L\x03\xbe\xf3\x04\x12\x04\x84\x03\
    \x208\n\x0c\n\x04\x05\0\x02M\x12\x04\x85\x03\x02=\n\r\n\x05\x05\0\x02M\
    \x01\x12\x04\x85\x03\x02\x1d\n\r\n\x05\x05\0\x02M\x02\x12\x04\x85\x03\
    \x1e!\n\r\n\x05\x05\0\x02M\x03\x12\x04\x85\x03\"<\n\x10\n\x08\x05\0\x02M\
    \x03\xbe\xf3\x04\x12\x04\x85\x03#;\n2\n\x04\x05\0\x02N\x12\x04\x88\x03\
    \x02f\x1a$\x20To\x20write\x20bulk\x20operations\x20to\x20the\x20DB\n\n\r\
    \n\x05\x05\0\x02N\x01\x12\x04\x88\x03\x02\x13\n\r\n\x05\x05\0\x02N\x02\
    \x12\x04\x88\x03\x16\x19\n\r\n\x05\x05\0\x02N\x03\x12\x04\x88\x03\x1ae\n\
    \x10\n\x08\x05\0\x02N\x03\xbe\xf3\x04\x12\x04\x88\x03\x1b3\n\x11\n\t\x05\
    \0\x02N\x03\xbf\xf3\x04\0\x12\x04\x88\x035d\n3\n\x04\x05\0\x02O\x12\x04\
    \x8b\x03\x025\x1a%\x20To\x20Read\x20Bulk\x20Operations\x20from\x20the\
    \x20DB\n\n\r\n\x05\x05\0\x02O\x01\x12\x04\x8b\x03\x02\x13\n\r\n\x05\x05\
    \0\x02O\x02\x12\x04\x8b\x03\x16\x19\n\r\n\x05\x05\0\x02O\x03\x12\x04\x8b\
    \x03\x1a4\n\x10\n\x08\x05\0\x02O\x03\xbe\xf3\x04\x12\x04\x8b\x03\x1b3\n7\
    \n\x04\x05\0\x02P\x12\x06\x8e\x03\x02\x8f\x035\x1a'\x20To\x20Delete\x20B\
    ulk\x20Operations\x20from\x20the\x20DB\n\n\r\n\x05\x05\0\x02P\x01\x12\
    \x04\x8e\x03\x02\x16\n\r\n\x05\x05\0\x02P\x02\x12\x04\x8e\x03\x19\x1c\n\
    \x0f\n\x05\x05\0\x02P\x03\x12\x06\x8e\x03\x1d\x8f\x034\n\x10\n\x08\x05\0\
    \x02P\x03\xbe\xf3\x04\x12\x04\x8e\x03\x1e6\n\x11\n\t\x05\0\x02P\x03\xbf\
    \xf3\x04\0\x12\x04\x8e\x038g\n\x11\n\t\x05\0\x02P\x03\xbf\xf3\x04\x01\
    \x12\x04\x8f\x03\x043\nI\n\x04\x05\0\x02Q\x12\x04\x92\x03\x02\x1c\x1a;\
    \x20To\x20read\x20historical\x20usage\x20from\x20usage.dashboard_items\
    \x20table\n\n\r\n\x05\x05\0\x02Q\x01\x12\x04\x92\x03\x02\x15\n\r\n\x05\
    \x05\0\x02Q\x02\x12\x04\x92\x03\x18\x1b\nO\n\x04\x05\0\x02R\x12\x04\x95\
    \x03\x02/\x1aA\x20To\x20read\x20uploaded\x20files\x20and\x20archives\x20\
    info\x20from\x20Uploads\x20endpoints\n\n\r\n\x05\x05\0\x02R\x01\x12\x04\
    \x95\x03\x02\r\n\r\n\x05\x05\0\x02R\x02\x12\x04\x95\x03\x10\x13\n\r\n\
    \x05\x05\0\x02R\x03\x12\x04\x95\x03\x14.\n\x10\n\x08\x05\0\x02R\x03\xbe\
    \xf3\x04\x12\x04\x95\x03\x15-\nK\n\x04\x05\0\x02S\x12\x06\x98\x03\x02\
    \x99\x03/\x1a;\x20To\x20upload\x20files\x20or\x20archives\x20through\x20\
    the\x20Uploads\x20endpoints\n\n\r\n\x05\x05\0\x02S\x01\x12\x04\x98\x03\
    \x02\r\n\r\n\x05\x05\0\x02S\x02\x12\x04\x98\x03\x10\x13\n\x0f\n\x05\x05\
    \0\x02S\x03\x12\x06\x98\x03\x14\x99\x03.\n\x10\n\x08\x05\0\x02S\x03\xbe\
    \xf3\x04\x12\x04\x98\x03\x15-\n\x11\n\t\x05\0\x02S\x03\xbf\xf3\x04\0\x12\
    \x04\x99\x03\x04-\n\x0e\n\x04\x05\0\x02T\x12\x06\x9b\x03\x02\x9d\x03/\n\
    \r\n\x05\x05\0\x02T\x01\x12\x04\x9b\x03\x02\x10\n\r\n\x05\x05\0\x02T\x02\
    \x12\x04\x9b\x03\x13\x16\n\x0f\n\x05\x05\0\x02T\x03\x12\x06\x9b\x03\x17\
    \x9d\x03.\n\x10\n\x08\x05\0\x02T\x03\xbe\xf3\x04\x12\x04\x9b\x03\x180\n\
    \x11\n\t\x05\0\x02T\x03\xbf\xf3\x04\0\x12\x04\x9c\x03\x04-\n\x11\n\t\x05\
    \0\x02T\x03\xbf\xf3\x04\x01\x12\x04\x9d\x03\x04-\n)\n\x04\x05\0\x02U\x12\
    \x04\xa0\x03\x02/\x1a\x1b\x20To\x20control\x20remote\x20runners\n\n\r\n\
    \x05\x05\0\x02U\x01\x12\x04\xa0\x03\x02\r\n\r\n\x05\x05\0\x02U\x02\x12\
    \x04\xa0\x03\x10\x13\n\r\n\x05\x05\0\x02U\x03\x12\x04\xa0\x03\x14.\n\x10\
    \n\x08\x05\0\x02U\x03\xbe\xf3\x04\x12\x04\xa0\x03\x15-\n\x0e\n\x04\x05\0\
    \x02V\x12\x06\xa2\x03\x02\xa3\x03/\n\r\n\x05\x05\0\x02V\x01\x12\x04\xa2\
    \x03\x02\r\n\r\n\x05\x05\0\x02V\x02\x12\x04\xa2\x03\x10\x13\n\x0f\n\x05\
    \x05\0\x02V\x03\x12\x06\xa2\x03\x14\xa3\x03.\n\x10\n\x08\x05\0\x02V\x03\
    \xbe\xf3\x04\x12\x04\xa2\x03\x15-\n\x11\n\t\x05\0\x02V\x03\xbf\xf3\x04\0\
    \x12\x04\xa3\x03\x04-\n\x0e\n\x04\x05\0\x02W\x12\x06\xa5\x03\x02\xa7\x03\
    /\n\r\n\x05\x05\0\x02W\x01\x12\x04\xa5\x03\x02\x10\n\r\n\x05\x05\0\x02W\
    \x02\x12\x04\xa5\x03\x13\x16\n\x0f\n\x05\x05\0\x02W\x03\x12\x06\xa5\x03\
    \x17\xa7\x03.\n\x10\n\x08\x05\0\x02W\x03\xbe\xf3\x04\x12\x04\xa5\x03\x18\
    0\n\x11\n\t\x05\0\x02W\x03\xbf\xf3\x04\0\x12\x04\xa6\x03\x04-\n\x11\n\t\
    \x05\0\x02W\x03\xbf\xf3\x04\x01\x12\x04\xa7\x03\x04-\n\x0c\n\x04\x05\0\
    \x02X\x12\x04\xa9\x03\x023\n\r\n\x05\x05\0\x02X\x01\x12\x04\xa9\x03\x02\
    \x11\n\r\n\x05\x05\0\x02X\x02\x12\x04\xa9\x03\x14\x17\n\r\n\x05\x05\0\
    \x02X\x03\x12\x04\xa9\x03\x182\n\x10\n\x08\x05\0\x02X\x03\xbe\xf3\x04\
    \x12\x04\xa9\x03\x191\n\x0e\n\x04\x05\0\x02Y\x12\x06\xab\x03\x02\xac\x03\
    3\n\r\n\x05\x05\0\x02Y\x01\x12\x04\xab\x03\x02\x11\n\r\n\x05\x05\0\x02Y\
    \x02\x12\x04\xab\x03\x14\x17\n\x0f\n\x05\x05\0\x02Y\x03\x12\x06\xab\x03\
    \x18\xac\x032\n\x10\n\x08\x05\0\x02Y\x03\xbe\xf3\x04\x12\x04\xab\x03\x19\
    1\n\x11\n\t\x05\0\x02Y\x03\xbf\xf3\x04\0\x12\x04\xac\x03\x041\n\x0b\n\
    \x01\x07\x12\x06\xc3\x03\0\xca\x03\x01\n\x95\x01\n\x02\x07\0\x12\x04\xc6\
    \x03\x02\x1f\x1a\x88\x01\x20indicates\x20whether\x20the\x20given\x20scop\
    e\x20should\x20be\x20returned\x20by\x20the\x20Get\x20/scopes/\x20call\n\
    \x20or\x20any\x20other\x20call\x20that\x20returns\x20list\x20of\x20avail\
    able\x20perms.\n\n\x0b\n\x03\x07\0\x02\x12\x04\xc3\x03\x07'\n\x0b\n\x03\
    \x07\0\x05\x12\x04\xc6\x03\x02\x06\n\x0b\n\x03\x07\0\x01\x12\x04\xc6\x03\
    \x07\x16\n\x0b\n\x03\x07\0\x03\x12\x04\xc6\x03\x19\x1e\n\xaa\x01\n\x02\
    \x07\x01\x12\x04\xc9\x03\x02/\x1a\x9d\x01\x20TODO:\x20We\x20have\x20no\
    \x20way\x20of\x20picking\x20extension\x20field\x20numbers\x20within\x20c\
    larifai\x20to\x20guarantee\n\x20uniqueness.\x20\x20Note:\x2050000-99999\
    \x20are\x20for\x20organizational\x20use\x20(like\x20this)\n\n\x0b\n\x03\
    \x07\x01\x02\x12\x04\xc3\x03\x07'\n\x0b\n\x03\x07\x01\x04\x12\x04\xc9\
    \x03\x02\n\n\x0b\n\x03\x07\x01\x06\x12\x04\xc9\x03\x0b\x0c\n\x0b\n\x03\
    \x07\x01\x01\x12\x04\xc9\x03\r&\n\x0b\n\x03\x07\x01\x03\x12\x04\xc9\x03)\
    .b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ScopeList::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(S::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
