[package]
name = "clarifai-rust-grpc"
version = "0.1.0"
authors = ["Rok Povsic <rok.povsic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpcio = "0.6.0"
protobuf = "2.0"
futures = "0.3"
