name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15, macos-11.0, windows-2019 ]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          export LIBCLANG_PATH="C:\Program Files\LLVM\bin"
          choco install -y llvm
        fi
        cargo build --verbose
    - name: Run tests
      shell: bash
      env:
        CLARIFAI_API_KEY: ${{ secrets.CLARIFAI_API_KEY }}
        CLARIFAI_GRPC_BASE: ${{ secrets.CLARIFAI_GRPC_BASE }}
      run: |
        if [[ "$RUNNER_OS" == "macOS" || "$RUNNER_OS" == "Windows" ]]; then
            curl -Lo roots.pem https://raw.githubusercontent.com/grpc/grpc/master/etc/roots.pem
            export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH="$PWD/roots.pem"
        fi
        cargo test --verbose
